//! Survey trigger handlers
//!
//! Auto-generated by backbone-cli. Do not edit manually.

use std::sync::Arc;
use async_trait::async_trait;
use backbone_core::trigger::{
    ActionExecutor, TriggerContext, TriggerContextMut, TriggerEvent, TriggerHandler, TriggerRegistry,
};

use crate::domain::entity::Survey;

pub type SurveyTriggerEvent      = TriggerEvent;
pub type SurveyTriggerContext    = TriggerContext<Survey>;
pub type SurveyTriggerContextMut = TriggerContextMut<Survey>;
pub type SurveyActionExecutor    = ActionExecutor;
pub type SurveyTriggerRegistry   = TriggerRegistry<Survey>;
pub type SurveyTriggerHandlerObj =
    dyn TriggerHandler<TriggerContext<Survey>, TriggerEvent>;

// State machine trigger handlers

/// Create a default registry pre-populated with all handlers for Survey.
pub fn survey_trigger_registry() -> SurveyTriggerRegistry {
    TriggerRegistry::build(|r| {
    })
}
