//! UserInput trigger handlers
//!
//! Auto-generated by backbone-cli. Do not edit manually.

use std::sync::Arc;
use async_trait::async_trait;
use backbone_core::trigger::{
    ActionExecutor, TriggerContext, TriggerContextMut, TriggerEvent, TriggerHandler, TriggerRegistry,
};

use crate::domain::entity::UserInput;

pub type UserInputTriggerEvent      = TriggerEvent;
pub type UserInputTriggerContext    = TriggerContext<UserInput>;
pub type UserInputTriggerContextMut = TriggerContextMut<UserInput>;
pub type UserInputActionExecutor    = ActionExecutor;
pub type UserInputTriggerRegistry   = TriggerRegistry<UserInput>;
pub type UserInputTriggerHandlerObj =
    dyn TriggerHandler<TriggerContext<UserInput>, TriggerEvent>;

// State machine trigger handlers

/// Create a default registry pre-populated with all handlers for UserInput.
pub fn user_input_trigger_registry() -> UserInputTriggerRegistry {
    TriggerRegistry::build(|r| {
    })
}
