//! State machine for survey_input_state workflow
//!
//! Generated by metaphor-schema

use serde::{Deserialize, Serialize};
use std::str::FromStr;

/// States for survey_input_state workflow
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum survey_input_stateState {
    /// Initial state
    New,
    InProgress,
    /// Final state
    Done,
}

impl Default for survey_input_stateState {
    fn default() -> Self {
        Self::New
    }
}

impl std::fmt::Display for survey_input_stateState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::New => write!(f, "new"),
            Self::InProgress => write!(f, "in_progress"),
            Self::Done => write!(f, "done"),
        }
    }
}

impl FromStr for survey_input_stateState {
    type Err = StateMachineError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "new" => Ok(Self::New),
            "in_progress" => Ok(Self::InProgress),
            "done" => Ok(Self::Done),
            _ => Err(StateMachineError::InvalidState(s.to_string())),
        }
    }
}

impl survey_input_stateState {
    /// Check if this is the initial state
    pub fn is_initial(&self) -> bool {
        matches!(self, Self::New)
    }

    /// Check if this is a final state
    pub fn is_final(&self) -> bool {
        matches!(self, Self::Done)
    }

    /// Get all possible states
    pub fn all() -> Vec<Self> {
        vec![
            Self::New,
            Self::InProgress,
            Self::Done,
        ]
    }
}

/// Transitions for survey_input_state workflow
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum survey_input_stateTransition {
    /// new -> in_progress
    Begin,
    /// in_progress -> done
    MarkDone,
    /// in_progress -> done
    SessionBulkDone,
}

impl std::fmt::Display for survey_input_stateTransition {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Begin => write!(f, "begin"),
            Self::MarkDone => write!(f, "mark_done"),
            Self::SessionBulkDone => write!(f, "session_bulk_done"),
        }
    }
}

impl FromStr for survey_input_stateTransition {
    type Err = StateMachineError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "begin" => Ok(Self::Begin),
            "mark_done" => Ok(Self::MarkDone),
            "session_bulk_done" => Ok(Self::SessionBulkDone),
            _ => Err(StateMachineError::InvalidTransition(s.to_string())),
        }
    }
}

impl survey_input_stateTransition {
    /// Get the target state of this transition
    pub fn target_state(&self) -> survey_input_stateState {
        match self {
            Self::Begin => survey_input_stateState::InProgress,
            Self::MarkDone => survey_input_stateState::Done,
            Self::SessionBulkDone => survey_input_stateState::Done,
        }
    }

    /// Get all transitions
    pub fn all() -> Vec<Self> {
        vec![
            Self::Begin,
            Self::MarkDone,
            Self::SessionBulkDone,
        ]
    }

    /// Get allowed roles for this transition
    pub fn allowed_roles(&self) -> &'static [&'static str] {
        match self {
            Self::Begin => &[],
            Self::MarkDone => &[],
            Self::SessionBulkDone => &[],
        }
    }
}

use super::StateMachineError;

/// State machine for survey_input_state workflow
#[derive(Debug, Clone)]
pub struct survey_input_stateStateMachine {
    current_state: survey_input_stateState,
}

impl survey_input_stateStateMachine {
    /// Create a new state machine with initial state
    pub fn new() -> Self {
        Self {
            current_state: survey_input_stateState::default(),
        }
    }

    /// Create from an existing state
    pub fn from_state(state: survey_input_stateState) -> Self {
        Self { current_state: state }
    }

    /// Get the current state
    pub fn current_state(&self) -> survey_input_stateState {
        self.current_state
    }

    /// Check if a transition is allowed from the current state
    pub fn can_transition(&self, transition: survey_input_stateTransition) -> bool {
        if matches!(self.current_state, survey_input_stateState::Done) {
            return false;
        }

        match (self.current_state, transition) {
            (survey_input_stateState::New, survey_input_stateTransition::Begin) => true,
            (survey_input_stateState::InProgress, survey_input_stateTransition::MarkDone) => true,
            (survey_input_stateState::InProgress, survey_input_stateTransition::SessionBulkDone) => true,
            _ => false,
        }
    }

    /// Check if a transition is allowed for a given role
    pub fn can_transition_with_role(&self, transition: survey_input_stateTransition, role: &str) -> bool {
        if !self.can_transition(transition) {
            return false;
        }

        let allowed_roles = transition.allowed_roles();
        if allowed_roles.is_empty() {
            return true; // No role restriction
        }

        allowed_roles.iter().any(|r| *r == role || *r == "*")
    }

    /// Apply a transition, returning the new state
    pub fn transition(&mut self, transition: survey_input_stateTransition) -> Result<survey_input_stateState, StateMachineError> {
        if !self.can_transition(transition) {
            return Err(StateMachineError::TransitionNotAllowed {
                transition: transition.to_string(),
                from: self.current_state.to_string(),
            });
        }

        self.current_state = transition.target_state();
        Ok(self.current_state)
    }

    /// Apply a transition with role check
    pub fn transition_with_role(&mut self, transition: survey_input_stateTransition, role: &str) -> Result<survey_input_stateState, StateMachineError> {
        // Check basic transition validity first
        if !self.can_transition(transition) {
            return Err(StateMachineError::TransitionNotAllowed {
                transition: transition.to_string(),
                from: self.current_state.to_string(),
            });
        }

        // Check role authorization
        if !self.can_transition_with_role(transition, role) {
            return Err(StateMachineError::RoleNotAuthorized {
                role: role.to_string(),
                transition: transition.to_string(),
            });
        }

        self.current_state = transition.target_state();
        Ok(self.current_state)
    }

    /// Get all available transitions from the current state
    pub fn available_transitions(&self) -> Vec<survey_input_stateTransition> {
        survey_input_stateTransition::all()
            .into_iter()
            .filter(|t| self.can_transition(*t))
            .collect()
    }

    /// Get all available transitions for a given role
    pub fn available_transitions_for_role(&self, role: &str) -> Vec<survey_input_stateTransition> {
        survey_input_stateTransition::all()
            .into_iter()
            .filter(|t| self.can_transition_with_role(*t, role))
            .collect()
    }

    /// Attempt to transition directly to a target state.
    ///
    /// Finds any transition that leads to the target state and applies it.
    /// Returns Err if no valid transition leads from current state to target.
    pub fn transition_to_state(&mut self, target: survey_input_stateState) -> Result<survey_input_stateState, StateMachineError> {
        let valid = survey_input_stateTransition::all().into_iter()
            .filter(|t| self.can_transition(*t))
            .find(|t| t.target_state() == target);
        match valid {
            Some(t) => self.transition(t),
            None => Err(StateMachineError::TransitionNotAllowed {
                transition: target.to_string(),
                from: self.current_state.to_string(),
            }),
        }
    }
}

impl Default for survey_input_stateStateMachine {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_initial_state() {
        let sm = survey_input_stateStateMachine::new();
        assert_eq!(sm.current_state(), survey_input_stateState::New);
        assert!(sm.current_state().is_initial());
    }

    #[test]
    fn test_valid_transition() {
        let mut sm = survey_input_stateStateMachine::from_state(survey_input_stateState::New);
        assert!(sm.can_transition(survey_input_stateTransition::Begin));
        let result = sm.transition(survey_input_stateTransition::Begin);
        assert!(result.is_ok());
        assert_eq!(sm.current_state(), survey_input_stateState::InProgress);
    }

    #[test]
    fn test_invalid_transition() {
        let mut sm = survey_input_stateStateMachine::from_state(survey_input_stateState::New);
        // MarkDone is not valid from New state
        let result = sm.transition(survey_input_stateTransition::MarkDone);
        assert!(result.is_err());
    }

    #[test]
    fn test_state_parsing() {
        let state: survey_input_stateState = "new".parse().unwrap();
        assert_eq!(state, survey_input_stateState::New);
    }

    #[test]
    fn test_available_transitions() {
        let sm = survey_input_stateStateMachine::new();
        let available = sm.available_transitions();
        // Should have at least some transitions available from initial state
        assert!(!available.is_empty() || sm.current_state().is_final());
    }
}
