//! State machine for survey_session_state workflow
//!
//! Generated by metaphor-schema

use serde::{Deserialize, Serialize};
use std::str::FromStr;

/// States for survey_session_state workflow
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum survey_session_stateState {
    /// Initial state
    Ready,
    InProgress,
}

impl Default for survey_session_stateState {
    fn default() -> Self {
        Self::Ready
    }
}

impl std::fmt::Display for survey_session_stateState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Ready => write!(f, "ready"),
            Self::InProgress => write!(f, "in_progress"),
        }
    }
}

impl FromStr for survey_session_stateState {
    type Err = StateMachineError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "ready" => Ok(Self::Ready),
            "in_progress" => Ok(Self::InProgress),
            _ => Err(StateMachineError::InvalidState(s.to_string())),
        }
    }
}

impl survey_session_stateState {
    /// Check if this is the initial state
    pub fn is_initial(&self) -> bool {
        matches!(self, Self::Ready)
    }

    /// Check if this is a final state
    pub fn is_final(&self) -> bool {
        false
    }

    /// Get all possible states
    pub fn all() -> Vec<Self> {
        vec![
            Self::Ready,
            Self::InProgress,
        ]
    }
}

/// Transitions for survey_session_state workflow
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum survey_session_stateTransition {
    /// null -> ready
    Arm,
    /// ready -> in_progress
    Start,
    /// ready, in_progress -> null
    End,
}

impl std::fmt::Display for survey_session_stateTransition {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Arm => write!(f, "arm"),
            Self::Start => write!(f, "start"),
            Self::End => write!(f, "end"),
        }
    }
}

impl FromStr for survey_session_stateTransition {
    type Err = StateMachineError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "arm" => Ok(Self::Arm),
            "start" => Ok(Self::Start),
            "end" => Ok(Self::End),
            _ => Err(StateMachineError::InvalidTransition(s.to_string())),
        }
    }
}

impl survey_session_stateTransition {
    /// Get the target state of this transition
    pub fn target_state(&self) -> Option<survey_session_stateState> {
        match self {
            Self::Arm => Some(survey_session_stateState::Ready),
            Self::Start => Some(survey_session_stateState::InProgress),
            Self::End => None,
        }
    }

    /// Get all transitions
    pub fn all() -> Vec<Self> {
        vec![
            Self::Arm,
            Self::Start,
            Self::End,
        ]
    }

    /// Get allowed roles for this transition
    pub fn allowed_roles(&self) -> &'static [&'static str] {
        match self {
            Self::Arm => &[],
            Self::Start => &[],
            Self::End => &[],
        }
    }
}

use super::StateMachineError;

/// State machine for survey_session_state workflow
#[derive(Debug, Clone)]
pub struct survey_session_stateStateMachine {
    current_state: Option<survey_session_stateState>,
}

impl survey_session_stateStateMachine {
    /// Create a new state machine at the null boundary — a nullable
    /// state field starts unset; the arm verb enters from here.
    pub fn new() -> Self {
        Self {
            current_state: None,
        }
    }

    /// Create from an existing state
    pub fn from_state(state: survey_session_stateState) -> Self {
        Self { current_state: Some(state) }
    }

    /// Create from the field's current value — `None`
    /// is the null boundary the verbs arm from and end to.
    pub fn from_opt_state(state: Option<survey_session_stateState>) -> Self {
        Self { current_state: state }
    }

    /// Get the current state
    pub fn current_state(&self) -> Option<survey_session_stateState> {
        self.current_state
    }

    /// Check if a transition is allowed from the current state
    pub fn can_transition(&self, transition: survey_session_stateTransition) -> bool {
        match (self.current_state, transition) {
            (None, survey_session_stateTransition::Arm) => true,
            (Some(survey_session_stateState::Ready), survey_session_stateTransition::Start) => true,
            (Some(survey_session_stateState::Ready), survey_session_stateTransition::End) => true,
            (Some(survey_session_stateState::InProgress), survey_session_stateTransition::End) => true,
            _ => false,
        }
    }

    /// Check if a transition is allowed for a given role
    pub fn can_transition_with_role(&self, transition: survey_session_stateTransition, role: &str) -> bool {
        if !self.can_transition(transition) {
            return false;
        }

        let allowed_roles = transition.allowed_roles();
        if allowed_roles.is_empty() {
            return true; // No role restriction
        }

        allowed_roles.iter().any(|r| *r == role || *r == "*")
    }

    /// Apply a transition, returning the new state
    pub fn transition(&mut self, transition: survey_session_stateTransition) -> Result<Option<survey_session_stateState>, StateMachineError> {
        if !self.can_transition(transition) {
            return Err(StateMachineError::TransitionNotAllowed {
                transition: transition.to_string(),
                from: self.current_state.map(|s| s.to_string()).unwrap_or_else(|| "null".to_string()),
            });
        }

        self.current_state = transition.target_state();
        Ok(self.current_state)
    }

    /// Apply a transition with role check
    pub fn transition_with_role(&mut self, transition: survey_session_stateTransition, role: &str) -> Result<Option<survey_session_stateState>, StateMachineError> {
        // Check basic transition validity first
        if !self.can_transition(transition) {
            return Err(StateMachineError::TransitionNotAllowed {
                transition: transition.to_string(),
                from: self.current_state.map(|s| s.to_string()).unwrap_or_else(|| "null".to_string()),
            });
        }

        // Check role authorization
        if !self.can_transition_with_role(transition, role) {
            return Err(StateMachineError::RoleNotAuthorized {
                role: role.to_string(),
                transition: transition.to_string(),
            });
        }

        self.current_state = transition.target_state();
        Ok(self.current_state)
    }

    /// Get all available transitions from the current state
    pub fn available_transitions(&self) -> Vec<survey_session_stateTransition> {
        survey_session_stateTransition::all()
            .into_iter()
            .filter(|t| self.can_transition(*t))
            .collect()
    }

    /// Get all available transitions for a given role
    pub fn available_transitions_for_role(&self, role: &str) -> Vec<survey_session_stateTransition> {
        survey_session_stateTransition::all()
            .into_iter()
            .filter(|t| self.can_transition_with_role(*t, role))
            .collect()
    }

    /// Attempt to transition directly to a target state.
    ///
    /// Finds any transition that leads to the target state and applies it.
    /// Returns Err if no valid transition leads from current state to target.
    pub fn transition_to_state(&mut self, target: Option<survey_session_stateState>) -> Result<Option<survey_session_stateState>, StateMachineError> {
        let valid = survey_session_stateTransition::all().into_iter()
            .filter(|t| self.can_transition(*t))
            .find(|t| t.target_state() == target);
        match valid {
            Some(t) => self.transition(t),
            None => Err(StateMachineError::TransitionNotAllowed {
                transition: target.map(|t| t.to_string()).unwrap_or_else(|| "null".to_string()),
                from: self.current_state.map(|s| s.to_string()).unwrap_or_else(|| "null".to_string()),
            }),
        }
    }
}

impl Default for survey_session_stateStateMachine {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_initial_state() {
        let sm = survey_session_stateStateMachine::new();
        assert_eq!(sm.current_state(), None);
    }

    #[test]
    fn test_valid_transition() {
        let mut sm = survey_session_stateStateMachine::new();
        assert!(sm.can_transition(survey_session_stateTransition::Arm));
        let result = sm.transition(survey_session_stateTransition::Arm);
        assert!(result.is_ok());
        assert_eq!(sm.current_state(), Some(survey_session_stateState::Ready));
    }

    #[test]
    fn test_invalid_transition() {
        let mut sm = survey_session_stateStateMachine::from_state(survey_session_stateState::Ready);
        // Arm is not valid from Ready state
        let result = sm.transition(survey_session_stateTransition::Arm);
        assert!(result.is_err());
    }

    #[test]
    fn test_state_parsing() {
        let state: survey_session_stateState = "ready".parse().unwrap();
        assert_eq!(state, survey_session_stateState::Ready);
    }

    #[test]
    fn test_available_transitions() {
        let sm = survey_session_stateStateMachine::new();
        let available = sm.available_transitions();
        // Should have at least some transitions available from initial state
        assert!(!available.is_empty() || sm.current_state().map_or(false, |s| s.is_final()));
    }
}
