//! DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides DTOs for the presentation layer,
//! with validation and OpenAPI schema support.

pub mod question_dto;
pub mod question_answer_dto;
pub mod survey_question_triggering_answer_dto;
pub mod survey_dto;
pub mod survey_survey_restrict_user_dto;
pub mod survey_survey_lang_dto;
pub mod user_input_dto;
pub mod user_input_line_dto;
pub mod survey_user_input_predefined_question_dto;

// Re-exports
pub use question_dto::{
    CreateQuestionDto,
    UpdateQuestionDto,
    PatchQuestionDto,
    QuestionResponseDto,
    QuestionListResponseDto,
    QuestionSummaryDto,
};
pub use question_answer_dto::{
    CreateQuestionAnswerDto,
    UpdateQuestionAnswerDto,
    PatchQuestionAnswerDto,
    QuestionAnswerResponseDto,
    QuestionAnswerListResponseDto,
    QuestionAnswerSummaryDto,
};
pub use survey_question_triggering_answer_dto::{
    CreateSurveyQuestionTriggeringAnswerDto,
    UpdateSurveyQuestionTriggeringAnswerDto,
    PatchSurveyQuestionTriggeringAnswerDto,
    SurveyQuestionTriggeringAnswerResponseDto,
    SurveyQuestionTriggeringAnswerListResponseDto,
    SurveyQuestionTriggeringAnswerSummaryDto,
};
pub use survey_dto::{
    CreateSurveyDto,
    UpdateSurveyDto,
    PatchSurveyDto,
    SurveyResponseDto,
    SurveyListResponseDto,
    SurveySummaryDto,
};
pub use survey_survey_restrict_user_dto::{
    CreateSurveySurveyRestrictUserDto,
    UpdateSurveySurveyRestrictUserDto,
    PatchSurveySurveyRestrictUserDto,
    SurveySurveyRestrictUserResponseDto,
    SurveySurveyRestrictUserListResponseDto,
    SurveySurveyRestrictUserSummaryDto,
};
pub use survey_survey_lang_dto::{
    CreateSurveySurveyLangDto,
    UpdateSurveySurveyLangDto,
    PatchSurveySurveyLangDto,
    SurveySurveyLangResponseDto,
    SurveySurveyLangListResponseDto,
    SurveySurveyLangSummaryDto,
};
pub use user_input_dto::{
    CreateUserInputDto,
    UpdateUserInputDto,
    PatchUserInputDto,
    UserInputResponseDto,
    UserInputListResponseDto,
    UserInputSummaryDto,
};
pub use user_input_line_dto::{
    CreateUserInputLineDto,
    UpdateUserInputLineDto,
    PatchUserInputLineDto,
    UserInputLineResponseDto,
    UserInputLineListResponseDto,
    UserInputLineSummaryDto,
};
pub use survey_user_input_predefined_question_dto::{
    CreateSurveyUserInputPredefinedQuestionDto,
    UpdateSurveyUserInputPredefinedQuestionDto,
    PatchSurveyUserInputPredefinedQuestionDto,
    SurveyUserInputPredefinedQuestionResponseDto,
    SurveyUserInputPredefinedQuestionListResponseDto,
    SurveyUserInputPredefinedQuestionSummaryDto,
};

// Common pagination types
use serde::Serialize;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

/// Pagination parameters for list requests
#[derive(Debug, Clone, Default, serde::Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct PaginationParams {
    /// Page number (1-indexed)
    #[serde(default = "default_page")]
    pub page: u32,
    /// Items per page
    #[serde(default = "default_per_page")]
    pub per_page: u32,
    /// Field to sort by
    pub sort_by: Option<String>,
    /// Sort order (asc/desc)
    pub sort_order: Option<String>,
}

fn default_page() -> u32 { 1 }
fn default_per_page() -> u32 { 20 }

/// API response wrapper
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApiResponse<T> {
    pub success: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<T>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<ApiError>,
}

#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct ApiError {
    pub code: String,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<serde_json::Value>,
}

impl<T> ApiResponse<T> {
    pub fn ok(data: T) -> Self {
        Self { success: true, data: Some(data), error: None }
    }

    pub fn err(code: impl Into<String>, message: impl Into<String>) -> Self {
        Self {
            success: false,
            data: None,
            error: Some(ApiError {
                code: code.into(),
                message: message.into(),
                details: None,
            }),
        }
    }
}
