//! Question DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Question;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::SurveyMatrixSubtype;
use crate::domain::entity::SurveyQuestionType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Question
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateQuestionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "survey_id")]
    pub survey_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_page")]
    pub is_page: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "question_type")]
    pub question_type: Option<SurveyQuestionType>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "question_placeholder")]
    pub question_placeholder: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "background_image")]
    pub background_image: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "random_questions_count")]
    pub random_questions_count: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_scored_question")]
    pub is_scored_question: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "answer_numerical_box")]
    pub answer_numerical_box: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "answer_date")]
    pub answer_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "answer_datetime")]
    pub answer_datetime: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    #[serde(alias = "answer_score")]
    pub answer_score: f64,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "save_as_email")]
    pub save_as_email: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "save_as_nickname")]
    pub save_as_nickname: bool,
    #[serde(alias = "matrix_subtype")]
    pub matrix_subtype: SurveyMatrixSubtype,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "scale_min")]
    pub scale_min: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "scale_max")]
    pub scale_max: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "scale_min_label")]
    pub scale_min_label: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "scale_mid_label")]
    pub scale_mid_label: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "scale_max_label")]
    pub scale_max_label: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_time_limited")]
    pub is_time_limited: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "time_limit")]
    pub time_limit: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_time_customized")]
    pub is_time_customized: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "comments_allowed")]
    pub comments_allowed: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "comments_message")]
    pub comments_message: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "comment_count_as_answer")]
    pub comment_count_as_answer: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "validation_required")]
    pub validation_required: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "validation_email")]
    pub validation_email: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "validation_length_min")]
    pub validation_length_min: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "validation_length_max")]
    pub validation_length_max: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "validation_min_float_value")]
    pub validation_min_float_value: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "validation_max_float_value")]
    pub validation_max_float_value: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "validation_min_date")]
    pub validation_min_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "validation_max_date")]
    pub validation_max_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "validation_min_datetime")]
    pub validation_min_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "validation_max_datetime")]
    pub validation_max_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "validation_error_msg")]
    pub validation_error_msg: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "constr_error_msg")]
    pub constr_error_msg: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "constr_mandatory")]
    pub constr_mandatory: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "page_id")]
    pub page_id: Option<Uuid>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Question
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateQuestionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "survey_id")]
    pub survey_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_page")]
    pub is_page: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "question_type")]
    pub question_type: Option<SurveyQuestionType>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "question_placeholder")]
    pub question_placeholder: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "background_image")]
    pub background_image: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "random_questions_count")]
    pub random_questions_count: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_scored_question")]
    pub is_scored_question: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "answer_numerical_box")]
    pub answer_numerical_box: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "answer_date")]
    pub answer_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "answer_datetime")]
    pub answer_datetime: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    #[serde(alias = "answer_score")]
    pub answer_score: f64,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "save_as_email")]
    pub save_as_email: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "save_as_nickname")]
    pub save_as_nickname: bool,
    #[serde(alias = "matrix_subtype")]
    pub matrix_subtype: SurveyMatrixSubtype,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "scale_min")]
    pub scale_min: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "scale_max")]
    pub scale_max: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "scale_min_label")]
    pub scale_min_label: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "scale_mid_label")]
    pub scale_mid_label: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "scale_max_label")]
    pub scale_max_label: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_time_limited")]
    pub is_time_limited: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "time_limit")]
    pub time_limit: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_time_customized")]
    pub is_time_customized: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "comments_allowed")]
    pub comments_allowed: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "comments_message")]
    pub comments_message: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "comment_count_as_answer")]
    pub comment_count_as_answer: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "validation_required")]
    pub validation_required: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "validation_email")]
    pub validation_email: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "validation_length_min")]
    pub validation_length_min: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "validation_length_max")]
    pub validation_length_max: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "validation_min_float_value")]
    pub validation_min_float_value: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "validation_max_float_value")]
    pub validation_max_float_value: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "validation_min_date")]
    pub validation_min_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "validation_max_date")]
    pub validation_max_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "validation_min_datetime")]
    pub validation_min_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "validation_max_datetime")]
    pub validation_max_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "validation_error_msg")]
    pub validation_error_msg: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "constr_error_msg")]
    pub constr_error_msg: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "constr_mandatory")]
    pub constr_mandatory: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "page_id")]
    pub page_id: Option<Uuid>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Question
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchQuestionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "survey_id")]
    pub survey_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sequence: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_page")]
    pub is_page: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "question_type")]
    pub question_type: Option<SurveyQuestionType>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "question_placeholder")]
    pub question_placeholder: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "background_image")]
    pub background_image: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "random_questions_count")]
    pub random_questions_count: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_scored_question")]
    pub is_scored_question: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "answer_numerical_box")]
    pub answer_numerical_box: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "answer_date")]
    pub answer_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "answer_datetime")]
    pub answer_datetime: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "answer_score")]
    pub answer_score: Option<f64>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "save_as_email")]
    pub save_as_email: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "save_as_nickname")]
    pub save_as_nickname: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "matrix_subtype")]
    pub matrix_subtype: Option<SurveyMatrixSubtype>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "scale_min")]
    pub scale_min: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "scale_max")]
    pub scale_max: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "scale_min_label")]
    pub scale_min_label: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "scale_mid_label")]
    pub scale_mid_label: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "scale_max_label")]
    pub scale_max_label: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_time_limited")]
    pub is_time_limited: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "time_limit")]
    pub time_limit: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_time_customized")]
    pub is_time_customized: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "comments_allowed")]
    pub comments_allowed: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "comments_message")]
    pub comments_message: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "comment_count_as_answer")]
    pub comment_count_as_answer: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "validation_required")]
    pub validation_required: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "validation_email")]
    pub validation_email: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "validation_length_min")]
    pub validation_length_min: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "validation_length_max")]
    pub validation_length_max: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "validation_min_float_value")]
    pub validation_min_float_value: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "validation_max_float_value")]
    pub validation_max_float_value: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "validation_min_date")]
    pub validation_min_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "validation_max_date")]
    pub validation_max_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "validation_min_datetime")]
    pub validation_min_datetime: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "validation_max_datetime")]
    pub validation_max_datetime: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "validation_error_msg")]
    pub validation_error_msg: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "constr_error_msg")]
    pub constr_error_msg: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "constr_mandatory")]
    pub constr_mandatory: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "page_id")]
    pub page_id: Option<Uuid>,
}

impl PatchQuestionDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.survey_id.is_some() || self.sequence.is_some() || self.is_page.is_some() || self.question_type.is_some() || self.title.is_some() || self.description.is_some() || self.question_placeholder.is_some() || self.background_image.is_some() || self.random_questions_count.is_some() || self.is_scored_question.is_some() || self.answer_numerical_box.is_some() || self.answer_date.is_some() || self.answer_datetime.is_some() || self.answer_score.is_some() || self.save_as_email.is_some() || self.save_as_nickname.is_some() || self.matrix_subtype.is_some() || self.scale_min.is_some() || self.scale_max.is_some() || self.scale_min_label.is_some() || self.scale_mid_label.is_some() || self.scale_max_label.is_some() || self.is_time_limited.is_some() || self.time_limit.is_some() || self.is_time_customized.is_some() || self.comments_allowed.is_some() || self.comments_message.is_some() || self.comment_count_as_answer.is_some() || self.validation_required.is_some() || self.validation_email.is_some() || self.validation_length_min.is_some() || self.validation_length_max.is_some() || self.validation_min_float_value.is_some() || self.validation_max_float_value.is_some() || self.validation_min_date.is_some() || self.validation_max_date.is_some() || self.validation_min_datetime.is_some() || self.validation_max_datetime.is_some() || self.validation_error_msg.is_some() || self.constr_error_msg.is_some() || self.constr_mandatory.is_some() || self.page_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Question entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct QuestionResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub survey_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_page: bool,
    pub question_type: Option<SurveyQuestionType>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    pub description: Option<String>,
    pub question_placeholder: Option<String>,
    pub background_image: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub random_questions_count: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_scored_question: bool,
    pub answer_numerical_box: Option<f64>,
    pub answer_date: Option<NaiveDate>,
    pub answer_datetime: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    pub answer_score: f64,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub save_as_email: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub save_as_nickname: bool,
    pub matrix_subtype: SurveyMatrixSubtype,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub scale_min: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub scale_max: i32,
    pub scale_min_label: Option<String>,
    pub scale_mid_label: Option<String>,
    pub scale_max_label: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_time_limited: bool,
    pub time_limit: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_time_customized: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub comments_allowed: bool,
    pub comments_message: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub comment_count_as_answer: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub validation_required: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub validation_email: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub validation_length_min: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub validation_length_max: i32,
    pub validation_min_float_value: Option<f64>,
    pub validation_max_float_value: Option<f64>,
    pub validation_min_date: Option<NaiveDate>,
    pub validation_max_date: Option<NaiveDate>,
    pub validation_min_datetime: Option<DateTime<Utc>>,
    pub validation_max_datetime: Option<DateTime<Utc>>,
    pub validation_error_msg: Option<String>,
    pub constr_error_msg: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub constr_mandatory: bool,
    pub page_id: Option<Uuid>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Question entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct QuestionListResponseDto {
    /// List of items
    pub items: Vec<QuestionResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl QuestionListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<QuestionResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct QuestionSummaryDto {
    pub id: Uuid,
    pub survey_id: Uuid,
    pub sequence: i32,
    pub is_page: bool,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Question> for QuestionResponseDto {
    fn from(entity: Question) -> Self {
        Self {
            id: entity.id,
            survey_id: entity.survey_id,
            sequence: entity.sequence,
            is_page: entity.is_page,
            question_type: entity.question_type,
            title: entity.title,
            description: entity.description,
            question_placeholder: entity.question_placeholder,
            background_image: entity.background_image,
            random_questions_count: entity.random_questions_count,
            is_scored_question: entity.is_scored_question,
            answer_numerical_box: entity.answer_numerical_box,
            answer_date: entity.answer_date,
            answer_datetime: entity.answer_datetime,
            answer_score: entity.answer_score,
            save_as_email: entity.save_as_email,
            save_as_nickname: entity.save_as_nickname,
            matrix_subtype: entity.matrix_subtype,
            scale_min: entity.scale_min,
            scale_max: entity.scale_max,
            scale_min_label: entity.scale_min_label,
            scale_mid_label: entity.scale_mid_label,
            scale_max_label: entity.scale_max_label,
            is_time_limited: entity.is_time_limited,
            time_limit: entity.time_limit,
            is_time_customized: entity.is_time_customized,
            comments_allowed: entity.comments_allowed,
            comments_message: entity.comments_message,
            comment_count_as_answer: entity.comment_count_as_answer,
            validation_required: entity.validation_required,
            validation_email: entity.validation_email,
            validation_length_min: entity.validation_length_min,
            validation_length_max: entity.validation_length_max,
            validation_min_float_value: entity.validation_min_float_value,
            validation_max_float_value: entity.validation_max_float_value,
            validation_min_date: entity.validation_min_date,
            validation_max_date: entity.validation_max_date,
            validation_min_datetime: entity.validation_min_datetime,
            validation_max_datetime: entity.validation_max_datetime,
            validation_error_msg: entity.validation_error_msg,
            constr_error_msg: entity.constr_error_msg,
            constr_mandatory: entity.constr_mandatory,
            page_id: entity.page_id,
            metadata: entity.metadata,
        }
    }
}

impl From<Question> for QuestionSummaryDto {
    fn from(entity: Question) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            survey_id: entity.survey_id,
            sequence: entity.sequence,
            is_page: entity.is_page,
            created_at,
        }
    }
}

impl From<CreateQuestionDto> for Question {
    fn from(dto: CreateQuestionDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            survey_id: dto.survey_id,
            sequence: dto.sequence,
            is_page: dto.is_page,
            question_type: dto.question_type,
            title: dto.title,
            description: dto.description,
            question_placeholder: dto.question_placeholder,
            background_image: dto.background_image,
            random_questions_count: dto.random_questions_count,
            is_scored_question: dto.is_scored_question,
            answer_numerical_box: dto.answer_numerical_box,
            answer_date: dto.answer_date,
            answer_datetime: dto.answer_datetime,
            answer_score: dto.answer_score,
            save_as_email: dto.save_as_email,
            save_as_nickname: dto.save_as_nickname,
            matrix_subtype: dto.matrix_subtype,
            scale_min: dto.scale_min,
            scale_max: dto.scale_max,
            scale_min_label: dto.scale_min_label,
            scale_mid_label: dto.scale_mid_label,
            scale_max_label: dto.scale_max_label,
            is_time_limited: dto.is_time_limited,
            time_limit: dto.time_limit,
            is_time_customized: dto.is_time_customized,
            comments_allowed: dto.comments_allowed,
            comments_message: dto.comments_message,
            comment_count_as_answer: dto.comment_count_as_answer,
            validation_required: dto.validation_required,
            validation_email: dto.validation_email,
            validation_length_min: dto.validation_length_min,
            validation_length_max: dto.validation_length_max,
            validation_min_float_value: dto.validation_min_float_value,
            validation_max_float_value: dto.validation_max_float_value,
            validation_min_date: dto.validation_min_date,
            validation_max_date: dto.validation_max_date,
            validation_min_datetime: dto.validation_min_datetime,
            validation_max_datetime: dto.validation_max_datetime,
            validation_error_msg: dto.validation_error_msg,
            constr_error_msg: dto.constr_error_msg,
            constr_mandatory: dto.constr_mandatory,
            page_id: dto.page_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Question> for QuestionResponseDto {
    fn from(entity: &Question) -> Self {
        Self {
            id: entity.id.clone(),
            survey_id: entity.survey_id.clone(),
            sequence: entity.sequence.clone(),
            is_page: entity.is_page.clone(),
            question_type: entity.question_type.clone(),
            title: entity.title.clone(),
            description: entity.description.clone(),
            question_placeholder: entity.question_placeholder.clone(),
            background_image: entity.background_image.clone(),
            random_questions_count: entity.random_questions_count.clone(),
            is_scored_question: entity.is_scored_question.clone(),
            answer_numerical_box: entity.answer_numerical_box.clone(),
            answer_date: entity.answer_date.clone(),
            answer_datetime: entity.answer_datetime.clone(),
            answer_score: entity.answer_score.clone(),
            save_as_email: entity.save_as_email.clone(),
            save_as_nickname: entity.save_as_nickname.clone(),
            matrix_subtype: entity.matrix_subtype.clone(),
            scale_min: entity.scale_min.clone(),
            scale_max: entity.scale_max.clone(),
            scale_min_label: entity.scale_min_label.clone(),
            scale_mid_label: entity.scale_mid_label.clone(),
            scale_max_label: entity.scale_max_label.clone(),
            is_time_limited: entity.is_time_limited.clone(),
            time_limit: entity.time_limit.clone(),
            is_time_customized: entity.is_time_customized.clone(),
            comments_allowed: entity.comments_allowed.clone(),
            comments_message: entity.comments_message.clone(),
            comment_count_as_answer: entity.comment_count_as_answer.clone(),
            validation_required: entity.validation_required.clone(),
            validation_email: entity.validation_email.clone(),
            validation_length_min: entity.validation_length_min.clone(),
            validation_length_max: entity.validation_length_max.clone(),
            validation_min_float_value: entity.validation_min_float_value.clone(),
            validation_max_float_value: entity.validation_max_float_value.clone(),
            validation_min_date: entity.validation_min_date.clone(),
            validation_max_date: entity.validation_max_date.clone(),
            validation_min_datetime: entity.validation_min_datetime.clone(),
            validation_max_datetime: entity.validation_max_datetime.clone(),
            validation_error_msg: entity.validation_error_msg.clone(),
            constr_error_msg: entity.constr_error_msg.clone(),
            constr_mandatory: entity.constr_mandatory.clone(),
            page_id: entity.page_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateQuestionDto> for Question {
    fn from_create_dto(dto: CreateQuestionDto) -> backbone_core::ServiceResult<Self> {
        Ok(Question::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateQuestionDto> for Question {
    fn apply_update(mut self, dto: UpdateQuestionDto) -> backbone_core::ServiceResult<Self> {
        self.survey_id = dto.survey_id;
        self.sequence = dto.sequence;
        self.is_page = dto.is_page;
        self.question_type = dto.question_type;
        self.title = dto.title;
        self.description = dto.description;
        self.question_placeholder = dto.question_placeholder;
        self.background_image = dto.background_image;
        self.random_questions_count = dto.random_questions_count;
        self.is_scored_question = dto.is_scored_question;
        self.answer_numerical_box = dto.answer_numerical_box;
        self.answer_date = dto.answer_date;
        self.answer_datetime = dto.answer_datetime;
        self.answer_score = dto.answer_score;
        self.save_as_email = dto.save_as_email;
        self.save_as_nickname = dto.save_as_nickname;
        self.matrix_subtype = dto.matrix_subtype;
        self.scale_min = dto.scale_min;
        self.scale_max = dto.scale_max;
        self.scale_min_label = dto.scale_min_label;
        self.scale_mid_label = dto.scale_mid_label;
        self.scale_max_label = dto.scale_max_label;
        self.is_time_limited = dto.is_time_limited;
        self.time_limit = dto.time_limit;
        self.is_time_customized = dto.is_time_customized;
        self.comments_allowed = dto.comments_allowed;
        self.comments_message = dto.comments_message;
        self.comment_count_as_answer = dto.comment_count_as_answer;
        self.validation_required = dto.validation_required;
        self.validation_email = dto.validation_email;
        self.validation_length_min = dto.validation_length_min;
        self.validation_length_max = dto.validation_length_max;
        self.validation_min_float_value = dto.validation_min_float_value;
        self.validation_max_float_value = dto.validation_max_float_value;
        self.validation_min_date = dto.validation_min_date;
        self.validation_max_date = dto.validation_max_date;
        self.validation_min_datetime = dto.validation_min_datetime;
        self.validation_max_datetime = dto.validation_max_datetime;
        self.validation_error_msg = dto.validation_error_msg;
        self.constr_error_msg = dto.constr_error_msg;
        self.constr_mandatory = dto.constr_mandatory;
        self.page_id = dto.page_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Question here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
