//! Survey DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Survey;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::SurveyAccessMode;
use crate::domain::entity::SurveyProgressionMode;
use crate::domain::entity::SurveyQuestionsLayout;
use crate::domain::entity::SurveyQuestionsSelection;
use crate::domain::entity::SurveyReportLayout;
use crate::domain::entity::SurveyScoringType;
use crate::domain::entity::SurveySessionState;
use crate::domain::entity::SurveySurveyType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Survey
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateSurveyDto {
    #[serde(alias = "survey_type")]
    pub survey_type: SurveySurveyType,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "description_done")]
    pub description_done: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "background_image")]
    pub background_image: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "user_id")]
    pub user_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "access_token")]
    pub access_token: String,
    #[serde(alias = "questions_layout")]
    pub questions_layout: SurveyQuestionsLayout,
    #[serde(alias = "questions_selection")]
    pub questions_selection: SurveyQuestionsSelection,
    #[serde(alias = "progression_mode")]
    pub progression_mode: SurveyProgressionMode,
    #[serde(alias = "access_mode")]
    pub access_mode: SurveyAccessMode,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "users_login_required")]
    pub users_login_required: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "users_can_go_back")]
    pub users_can_go_back: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_attempts_limited")]
    pub is_attempts_limited: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "attempts_limit")]
    pub attempts_limit: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_time_limited")]
    pub is_time_limited: bool,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    #[serde(alias = "time_limit")]
    pub time_limit: f64,
    #[serde(alias = "scoring_type")]
    pub scoring_type: SurveyScoringType,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    #[serde(alias = "scoring_success_min")]
    pub scoring_success_min: f64,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub certification: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "certification_mail_template_id")]
    pub certification_mail_template_id: Option<Uuid>,
    #[serde(alias = "certification_report_layout")]
    pub certification_report_layout: SurveyReportLayout,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "certification_give_badge")]
    pub certification_give_badge: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "certification_badge_key")]
    pub certification_badge_key: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "session_state")]
    pub session_state: Option<SurveySessionState>,
    #[cfg_attr(feature = "validation", validate(length(max = 16)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "session_code")]
    pub session_code: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "session_question_id")]
    pub session_question_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "session_start_time")]
    pub session_start_time: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "session_question_start_time")]
    pub session_question_start_time: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "session_speed_rating")]
    pub session_speed_rating: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "session_speed_rating_time_limit")]
    pub session_speed_rating_time_limit: Option<i32>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Survey
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateSurveyDto {
    #[serde(alias = "survey_type")]
    pub survey_type: SurveySurveyType,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "description_done")]
    pub description_done: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "background_image")]
    pub background_image: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "user_id")]
    pub user_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "access_token")]
    pub access_token: String,
    #[serde(alias = "questions_layout")]
    pub questions_layout: SurveyQuestionsLayout,
    #[serde(alias = "questions_selection")]
    pub questions_selection: SurveyQuestionsSelection,
    #[serde(alias = "progression_mode")]
    pub progression_mode: SurveyProgressionMode,
    #[serde(alias = "access_mode")]
    pub access_mode: SurveyAccessMode,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "users_login_required")]
    pub users_login_required: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "users_can_go_back")]
    pub users_can_go_back: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_attempts_limited")]
    pub is_attempts_limited: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "attempts_limit")]
    pub attempts_limit: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_time_limited")]
    pub is_time_limited: bool,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    #[serde(alias = "time_limit")]
    pub time_limit: f64,
    #[serde(alias = "scoring_type")]
    pub scoring_type: SurveyScoringType,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    #[serde(alias = "scoring_success_min")]
    pub scoring_success_min: f64,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub certification: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "certification_mail_template_id")]
    pub certification_mail_template_id: Option<Uuid>,
    #[serde(alias = "certification_report_layout")]
    pub certification_report_layout: SurveyReportLayout,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "certification_give_badge")]
    pub certification_give_badge: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "certification_badge_key")]
    pub certification_badge_key: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "session_state")]
    pub session_state: Option<SurveySessionState>,
    #[cfg_attr(feature = "validation", validate(length(max = 16)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "session_code")]
    pub session_code: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "session_question_id")]
    pub session_question_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "session_start_time")]
    pub session_start_time: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "session_question_start_time")]
    pub session_question_start_time: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "session_speed_rating")]
    pub session_speed_rating: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "session_speed_rating_time_limit")]
    pub session_speed_rating_time_limit: Option<i32>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Survey
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchSurveyDto {
    #[serde(skip_serializing_if = "Option::is_none", alias = "survey_type")]
    pub survey_type: Option<SurveySurveyType>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "description_done")]
    pub description_done: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "background_image")]
    pub background_image: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "user_id")]
    pub user_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "access_token")]
    pub access_token: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "questions_layout")]
    pub questions_layout: Option<SurveyQuestionsLayout>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "questions_selection")]
    pub questions_selection: Option<SurveyQuestionsSelection>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "progression_mode")]
    pub progression_mode: Option<SurveyProgressionMode>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "access_mode")]
    pub access_mode: Option<SurveyAccessMode>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "users_login_required")]
    pub users_login_required: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "users_can_go_back")]
    pub users_can_go_back: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_attempts_limited")]
    pub is_attempts_limited: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "attempts_limit")]
    pub attempts_limit: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_time_limited")]
    pub is_time_limited: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "time_limit")]
    pub time_limit: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "scoring_type")]
    pub scoring_type: Option<SurveyScoringType>,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "scoring_success_min")]
    pub scoring_success_min: Option<f64>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub certification: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "certification_mail_template_id")]
    pub certification_mail_template_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "certification_report_layout")]
    pub certification_report_layout: Option<SurveyReportLayout>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "certification_give_badge")]
    pub certification_give_badge: Option<bool>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "certification_badge_key")]
    pub certification_badge_key: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "session_state")]
    pub session_state: Option<SurveySessionState>,
    #[cfg_attr(feature = "validation", validate(length(max = 16)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "session_code")]
    pub session_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "session_question_id")]
    pub session_question_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "session_start_time")]
    pub session_start_time: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "session_question_start_time")]
    pub session_question_start_time: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "session_speed_rating")]
    pub session_speed_rating: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "session_speed_rating_time_limit")]
    pub session_speed_rating_time_limit: Option<i32>,
}

impl PatchSurveyDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.survey_type.is_some() || self.title.is_some() || self.description.is_some() || self.description_done.is_some() || self.background_image.is_some() || self.active.is_some() || self.user_id.is_some() || self.access_token.is_some() || self.questions_layout.is_some() || self.questions_selection.is_some() || self.progression_mode.is_some() || self.access_mode.is_some() || self.users_login_required.is_some() || self.users_can_go_back.is_some() || self.is_attempts_limited.is_some() || self.attempts_limit.is_some() || self.is_time_limited.is_some() || self.time_limit.is_some() || self.scoring_type.is_some() || self.scoring_success_min.is_some() || self.certification.is_some() || self.certification_mail_template_id.is_some() || self.certification_report_layout.is_some() || self.certification_give_badge.is_some() || self.certification_badge_key.is_some() || self.session_state.is_some() || self.session_code.is_some() || self.session_question_id.is_some() || self.session_start_time.is_some() || self.session_question_start_time.is_some() || self.session_speed_rating.is_some() || self.session_speed_rating_time_limit.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Survey entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SurveyResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    pub survey_type: SurveySurveyType,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    pub description: Option<String>,
    pub description_done: Option<String>,
    pub background_image: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    pub user_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub access_token: String,
    pub questions_layout: SurveyQuestionsLayout,
    pub questions_selection: SurveyQuestionsSelection,
    pub progression_mode: SurveyProgressionMode,
    pub access_mode: SurveyAccessMode,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub users_login_required: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub users_can_go_back: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_attempts_limited: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub attempts_limit: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_time_limited: bool,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    pub time_limit: f64,
    pub scoring_type: SurveyScoringType,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    pub scoring_success_min: f64,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub certification: bool,
    pub certification_mail_template_id: Option<Uuid>,
    pub certification_report_layout: SurveyReportLayout,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub certification_give_badge: bool,
    pub certification_badge_key: Option<String>,
    pub session_state: Option<SurveySessionState>,
    pub session_code: Option<String>,
    pub session_question_id: Option<Uuid>,
    pub session_start_time: Option<DateTime<Utc>>,
    pub session_question_start_time: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub session_speed_rating: bool,
    pub session_speed_rating_time_limit: Option<i32>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Survey entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SurveyListResponseDto {
    /// List of items
    pub items: Vec<SurveyResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl SurveyListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<SurveyResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SurveySummaryDto {
    pub id: Uuid,
    pub survey_type: SurveySurveyType,
    pub title: String,
    pub description: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Survey> for SurveyResponseDto {
    fn from(entity: Survey) -> Self {
        Self {
            id: entity.id,
            survey_type: entity.survey_type,
            title: entity.title,
            description: entity.description,
            description_done: entity.description_done,
            background_image: entity.background_image,
            active: entity.active,
            user_id: entity.user_id,
            access_token: entity.access_token,
            questions_layout: entity.questions_layout,
            questions_selection: entity.questions_selection,
            progression_mode: entity.progression_mode,
            access_mode: entity.access_mode,
            users_login_required: entity.users_login_required,
            users_can_go_back: entity.users_can_go_back,
            is_attempts_limited: entity.is_attempts_limited,
            attempts_limit: entity.attempts_limit,
            is_time_limited: entity.is_time_limited,
            time_limit: entity.time_limit,
            scoring_type: entity.scoring_type,
            scoring_success_min: entity.scoring_success_min,
            certification: entity.certification,
            certification_mail_template_id: entity.certification_mail_template_id,
            certification_report_layout: entity.certification_report_layout,
            certification_give_badge: entity.certification_give_badge,
            certification_badge_key: entity.certification_badge_key,
            session_state: entity.session_state,
            session_code: entity.session_code,
            session_question_id: entity.session_question_id,
            session_start_time: entity.session_start_time,
            session_question_start_time: entity.session_question_start_time,
            session_speed_rating: entity.session_speed_rating,
            session_speed_rating_time_limit: entity.session_speed_rating_time_limit,
            metadata: entity.metadata,
        }
    }
}

impl From<Survey> for SurveySummaryDto {
    fn from(entity: Survey) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            survey_type: entity.survey_type,
            title: entity.title,
            description: entity.description,
            created_at,
        }
    }
}

impl From<CreateSurveyDto> for Survey {
    fn from(dto: CreateSurveyDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            survey_type: dto.survey_type,
            title: dto.title,
            description: dto.description,
            description_done: dto.description_done,
            background_image: dto.background_image,
            active: dto.active,
            user_id: dto.user_id,
            access_token: dto.access_token,
            questions_layout: dto.questions_layout,
            questions_selection: dto.questions_selection,
            progression_mode: dto.progression_mode,
            access_mode: dto.access_mode,
            users_login_required: dto.users_login_required,
            users_can_go_back: dto.users_can_go_back,
            is_attempts_limited: dto.is_attempts_limited,
            attempts_limit: dto.attempts_limit,
            is_time_limited: dto.is_time_limited,
            time_limit: dto.time_limit,
            scoring_type: dto.scoring_type,
            scoring_success_min: dto.scoring_success_min,
            certification: dto.certification,
            certification_mail_template_id: dto.certification_mail_template_id,
            certification_report_layout: dto.certification_report_layout,
            certification_give_badge: dto.certification_give_badge,
            certification_badge_key: dto.certification_badge_key,
            session_state: dto.session_state,
            session_code: dto.session_code,
            session_question_id: dto.session_question_id,
            session_start_time: dto.session_start_time,
            session_question_start_time: dto.session_question_start_time,
            session_speed_rating: dto.session_speed_rating,
            session_speed_rating_time_limit: dto.session_speed_rating_time_limit,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Survey> for SurveyResponseDto {
    fn from(entity: &Survey) -> Self {
        Self {
            id: entity.id.clone(),
            survey_type: entity.survey_type.clone(),
            title: entity.title.clone(),
            description: entity.description.clone(),
            description_done: entity.description_done.clone(),
            background_image: entity.background_image.clone(),
            active: entity.active.clone(),
            user_id: entity.user_id.clone(),
            access_token: entity.access_token.clone(),
            questions_layout: entity.questions_layout.clone(),
            questions_selection: entity.questions_selection.clone(),
            progression_mode: entity.progression_mode.clone(),
            access_mode: entity.access_mode.clone(),
            users_login_required: entity.users_login_required.clone(),
            users_can_go_back: entity.users_can_go_back.clone(),
            is_attempts_limited: entity.is_attempts_limited.clone(),
            attempts_limit: entity.attempts_limit.clone(),
            is_time_limited: entity.is_time_limited.clone(),
            time_limit: entity.time_limit.clone(),
            scoring_type: entity.scoring_type.clone(),
            scoring_success_min: entity.scoring_success_min.clone(),
            certification: entity.certification.clone(),
            certification_mail_template_id: entity.certification_mail_template_id.clone(),
            certification_report_layout: entity.certification_report_layout.clone(),
            certification_give_badge: entity.certification_give_badge.clone(),
            certification_badge_key: entity.certification_badge_key.clone(),
            session_state: entity.session_state.clone(),
            session_code: entity.session_code.clone(),
            session_question_id: entity.session_question_id.clone(),
            session_start_time: entity.session_start_time.clone(),
            session_question_start_time: entity.session_question_start_time.clone(),
            session_speed_rating: entity.session_speed_rating.clone(),
            session_speed_rating_time_limit: entity.session_speed_rating_time_limit.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateSurveyDto> for Survey {
    fn from_create_dto(dto: CreateSurveyDto) -> backbone_core::ServiceResult<Self> {
        Ok(Survey::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateSurveyDto> for Survey {
    fn apply_update(mut self, dto: UpdateSurveyDto) -> backbone_core::ServiceResult<Self> {
        self.survey_type = dto.survey_type;
        self.title = dto.title;
        self.description = dto.description;
        self.description_done = dto.description_done;
        self.background_image = dto.background_image;
        self.active = dto.active;
        self.user_id = dto.user_id;
        self.access_token = dto.access_token;
        self.questions_layout = dto.questions_layout;
        self.questions_selection = dto.questions_selection;
        self.progression_mode = dto.progression_mode;
        self.access_mode = dto.access_mode;
        self.users_login_required = dto.users_login_required;
        self.users_can_go_back = dto.users_can_go_back;
        self.is_attempts_limited = dto.is_attempts_limited;
        self.attempts_limit = dto.attempts_limit;
        self.is_time_limited = dto.is_time_limited;
        self.time_limit = dto.time_limit;
        self.scoring_type = dto.scoring_type;
        self.scoring_success_min = dto.scoring_success_min;
        self.certification = dto.certification;
        self.certification_mail_template_id = dto.certification_mail_template_id;
        self.certification_report_layout = dto.certification_report_layout;
        self.certification_give_badge = dto.certification_give_badge;
        self.certification_badge_key = dto.certification_badge_key;
        self.session_state = dto.session_state;
        self.session_code = dto.session_code;
        self.session_question_id = dto.session_question_id;
        self.session_start_time = dto.session_start_time;
        self.session_question_start_time = dto.session_question_start_time;
        self.session_speed_rating = dto.session_speed_rating;
        self.session_speed_rating_time_limit = dto.session_speed_rating_time_limit;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Survey here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
