//! SurveyUserInputPredefinedQuestion DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::SurveyUserInputPredefinedQuestion;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new SurveyUserInputPredefinedQuestion
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateSurveyUserInputPredefinedQuestionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "user_input_id")]
    pub user_input_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "question_id")]
    pub question_id: Uuid,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a SurveyUserInputPredefinedQuestion
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateSurveyUserInputPredefinedQuestionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "user_input_id")]
    pub user_input_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "question_id")]
    pub question_id: Uuid,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a SurveyUserInputPredefinedQuestion
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchSurveyUserInputPredefinedQuestionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "user_input_id")]
    pub user_input_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "question_id")]
    pub question_id: Option<Uuid>,
}

impl PatchSurveyUserInputPredefinedQuestionDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.user_input_id.is_some() || self.question_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for SurveyUserInputPredefinedQuestion entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SurveyUserInputPredefinedQuestionResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub user_input_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub question_id: Uuid,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for SurveyUserInputPredefinedQuestion entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SurveyUserInputPredefinedQuestionListResponseDto {
    /// List of items
    pub items: Vec<SurveyUserInputPredefinedQuestionResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl SurveyUserInputPredefinedQuestionListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<SurveyUserInputPredefinedQuestionResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SurveyUserInputPredefinedQuestionSummaryDto {
    pub id: Uuid,
    pub user_input_id: Uuid,
    pub question_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<SurveyUserInputPredefinedQuestion> for SurveyUserInputPredefinedQuestionResponseDto {
    fn from(entity: SurveyUserInputPredefinedQuestion) -> Self {
        Self {
            id: entity.id,
            user_input_id: entity.user_input_id,
            question_id: entity.question_id,
            metadata: entity.metadata,
        }
    }
}

impl From<SurveyUserInputPredefinedQuestion> for SurveyUserInputPredefinedQuestionSummaryDto {
    fn from(entity: SurveyUserInputPredefinedQuestion) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            user_input_id: entity.user_input_id,
            question_id: entity.question_id,
            created_at,
        }
    }
}

impl From<CreateSurveyUserInputPredefinedQuestionDto> for SurveyUserInputPredefinedQuestion {
    fn from(dto: CreateSurveyUserInputPredefinedQuestionDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            user_input_id: dto.user_input_id,
            question_id: dto.question_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&SurveyUserInputPredefinedQuestion> for SurveyUserInputPredefinedQuestionResponseDto {
    fn from(entity: &SurveyUserInputPredefinedQuestion) -> Self {
        Self {
            id: entity.id.clone(),
            user_input_id: entity.user_input_id.clone(),
            question_id: entity.question_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateSurveyUserInputPredefinedQuestionDto> for SurveyUserInputPredefinedQuestion {
    fn from_create_dto(dto: CreateSurveyUserInputPredefinedQuestionDto) -> backbone_core::ServiceResult<Self> {
        Ok(SurveyUserInputPredefinedQuestion::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateSurveyUserInputPredefinedQuestionDto> for SurveyUserInputPredefinedQuestion {
    fn apply_update(mut self, dto: UpdateSurveyUserInputPredefinedQuestionDto) -> backbone_core::ServiceResult<Self> {
        self.user_input_id = dto.user_input_id;
        self.question_id = dto.question_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to SurveyUserInputPredefinedQuestion here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
