//! SurveySurveyLang DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::SurveySurveyLang;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new SurveySurveyLang
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateSurveySurveyLangDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "survey_id")]
    pub survey_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "lang_id")]
    pub lang_id: Uuid,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a SurveySurveyLang
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateSurveySurveyLangDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "survey_id")]
    pub survey_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "lang_id")]
    pub lang_id: Uuid,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a SurveySurveyLang
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchSurveySurveyLangDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "survey_id")]
    pub survey_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "lang_id")]
    pub lang_id: Option<Uuid>,
}

impl PatchSurveySurveyLangDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.survey_id.is_some() || self.lang_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for SurveySurveyLang entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SurveySurveyLangResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub survey_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub lang_id: Uuid,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for SurveySurveyLang entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SurveySurveyLangListResponseDto {
    /// List of items
    pub items: Vec<SurveySurveyLangResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl SurveySurveyLangListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<SurveySurveyLangResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SurveySurveyLangSummaryDto {
    pub id: Uuid,
    pub survey_id: Uuid,
    pub lang_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<SurveySurveyLang> for SurveySurveyLangResponseDto {
    fn from(entity: SurveySurveyLang) -> Self {
        Self {
            id: entity.id,
            survey_id: entity.survey_id,
            lang_id: entity.lang_id,
            metadata: entity.metadata,
        }
    }
}

impl From<SurveySurveyLang> for SurveySurveyLangSummaryDto {
    fn from(entity: SurveySurveyLang) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            survey_id: entity.survey_id,
            lang_id: entity.lang_id,
            created_at,
        }
    }
}

impl From<CreateSurveySurveyLangDto> for SurveySurveyLang {
    fn from(dto: CreateSurveySurveyLangDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            survey_id: dto.survey_id,
            lang_id: dto.lang_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&SurveySurveyLang> for SurveySurveyLangResponseDto {
    fn from(entity: &SurveySurveyLang) -> Self {
        Self {
            id: entity.id.clone(),
            survey_id: entity.survey_id.clone(),
            lang_id: entity.lang_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateSurveySurveyLangDto> for SurveySurveyLang {
    fn from_create_dto(dto: CreateSurveySurveyLangDto) -> backbone_core::ServiceResult<Self> {
        Ok(SurveySurveyLang::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateSurveySurveyLangDto> for SurveySurveyLang {
    fn apply_update(mut self, dto: UpdateSurveySurveyLangDto) -> backbone_core::ServiceResult<Self> {
        self.survey_id = dto.survey_id;
        self.lang_id = dto.lang_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to SurveySurveyLang here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
