//! SurveySurveyRestrictUser DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::SurveySurveyRestrictUser;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new SurveySurveyRestrictUser
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateSurveySurveyRestrictUserDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "survey_id")]
    pub survey_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "user_id")]
    pub user_id: Uuid,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a SurveySurveyRestrictUser
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateSurveySurveyRestrictUserDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "survey_id")]
    pub survey_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "user_id")]
    pub user_id: Uuid,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a SurveySurveyRestrictUser
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchSurveySurveyRestrictUserDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "survey_id")]
    pub survey_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "user_id")]
    pub user_id: Option<Uuid>,
}

impl PatchSurveySurveyRestrictUserDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.survey_id.is_some() || self.user_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for SurveySurveyRestrictUser entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SurveySurveyRestrictUserResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub survey_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub user_id: Uuid,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for SurveySurveyRestrictUser entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SurveySurveyRestrictUserListResponseDto {
    /// List of items
    pub items: Vec<SurveySurveyRestrictUserResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl SurveySurveyRestrictUserListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<SurveySurveyRestrictUserResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SurveySurveyRestrictUserSummaryDto {
    pub id: Uuid,
    pub survey_id: Uuid,
    pub user_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<SurveySurveyRestrictUser> for SurveySurveyRestrictUserResponseDto {
    fn from(entity: SurveySurveyRestrictUser) -> Self {
        Self {
            id: entity.id,
            survey_id: entity.survey_id,
            user_id: entity.user_id,
            metadata: entity.metadata,
        }
    }
}

impl From<SurveySurveyRestrictUser> for SurveySurveyRestrictUserSummaryDto {
    fn from(entity: SurveySurveyRestrictUser) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            survey_id: entity.survey_id,
            user_id: entity.user_id,
            created_at,
        }
    }
}

impl From<CreateSurveySurveyRestrictUserDto> for SurveySurveyRestrictUser {
    fn from(dto: CreateSurveySurveyRestrictUserDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            survey_id: dto.survey_id,
            user_id: dto.user_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&SurveySurveyRestrictUser> for SurveySurveyRestrictUserResponseDto {
    fn from(entity: &SurveySurveyRestrictUser) -> Self {
        Self {
            id: entity.id.clone(),
            survey_id: entity.survey_id.clone(),
            user_id: entity.user_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateSurveySurveyRestrictUserDto> for SurveySurveyRestrictUser {
    fn from_create_dto(dto: CreateSurveySurveyRestrictUserDto) -> backbone_core::ServiceResult<Self> {
        Ok(SurveySurveyRestrictUser::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateSurveySurveyRestrictUserDto> for SurveySurveyRestrictUser {
    fn apply_update(mut self, dto: UpdateSurveySurveyRestrictUserDto) -> backbone_core::ServiceResult<Self> {
        self.survey_id = dto.survey_id;
        self.user_id = dto.user_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to SurveySurveyRestrictUser here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
