//! UserInput DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::UserInput;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::SurveyInputState;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new UserInput
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateUserInputDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "survey_id")]
    pub survey_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "token_nonce")]
    pub token_nonce: String,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "token_expires_at")]
    pub token_expires_at: DateTime<Utc>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "invite_token")]
    pub invite_token: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "partner_id")]
    pub partner_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 320)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub nickname: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "user_id")]
    pub user_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "wire_identity_key")]
    pub wire_identity_key: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "test_entry")]
    pub test_entry: bool,
    pub state: SurveyInputState,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "start_datetime")]
    pub start_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "end_datetime")]
    pub end_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_session_answer")]
    pub is_session_answer: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_displayed_page_id")]
    pub last_displayed_page_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    #[serde(alias = "scoring_percentage")]
    pub scoring_percentage: f64,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    #[serde(alias = "scoring_total")]
    pub scoring_total: f64,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "scoring_success")]
    pub scoring_success: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a UserInput
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateUserInputDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "survey_id")]
    pub survey_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "token_nonce")]
    pub token_nonce: String,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "token_expires_at")]
    pub token_expires_at: DateTime<Utc>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "invite_token")]
    pub invite_token: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "partner_id")]
    pub partner_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 320)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub nickname: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "user_id")]
    pub user_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "wire_identity_key")]
    pub wire_identity_key: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "test_entry")]
    pub test_entry: bool,
    pub state: SurveyInputState,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "start_datetime")]
    pub start_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "end_datetime")]
    pub end_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_session_answer")]
    pub is_session_answer: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_displayed_page_id")]
    pub last_displayed_page_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    #[serde(alias = "scoring_percentage")]
    pub scoring_percentage: f64,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    #[serde(alias = "scoring_total")]
    pub scoring_total: f64,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "scoring_success")]
    pub scoring_success: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a UserInput
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchUserInputDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "survey_id")]
    pub survey_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "token_nonce")]
    pub token_nonce: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "token_expires_at")]
    pub token_expires_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "invite_token")]
    pub invite_token: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "partner_id")]
    pub partner_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 320)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nickname: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "user_id")]
    pub user_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "wire_identity_key")]
    pub wire_identity_key: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "test_entry")]
    pub test_entry: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<SurveyInputState>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "start_datetime")]
    pub start_datetime: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "end_datetime")]
    pub end_datetime: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deadline: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_session_answer")]
    pub is_session_answer: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_displayed_page_id")]
    pub last_displayed_page_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "scoring_percentage")]
    pub scoring_percentage: Option<f64>,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "scoring_total")]
    pub scoring_total: Option<f64>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "scoring_success")]
    pub scoring_success: Option<bool>,
}

impl PatchUserInputDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.survey_id.is_some() || self.token_nonce.is_some() || self.token_expires_at.is_some() || self.invite_token.is_some() || self.partner_id.is_some() || self.email.is_some() || self.nickname.is_some() || self.user_id.is_some() || self.wire_identity_key.is_some() || self.test_entry.is_some() || self.state.is_some() || self.start_datetime.is_some() || self.end_datetime.is_some() || self.deadline.is_some() || self.is_session_answer.is_some() || self.last_displayed_page_id.is_some() || self.scoring_percentage.is_some() || self.scoring_total.is_some() || self.scoring_success.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for UserInput entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct UserInputResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub survey_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub token_nonce: String,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub token_expires_at: DateTime<Utc>,
    pub invite_token: Option<String>,
    pub partner_id: Option<Uuid>,
    pub email: Option<String>,
    pub nickname: Option<String>,
    pub user_id: Option<Uuid>,
    pub wire_identity_key: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub test_entry: bool,
    pub state: SurveyInputState,
    pub start_datetime: Option<DateTime<Utc>>,
    pub end_datetime: Option<DateTime<Utc>>,
    pub deadline: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_session_answer: bool,
    pub last_displayed_page_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    pub scoring_percentage: f64,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    pub scoring_total: f64,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub scoring_success: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for UserInput entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct UserInputListResponseDto {
    /// List of items
    pub items: Vec<UserInputResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl UserInputListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<UserInputResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct UserInputSummaryDto {
    pub id: Uuid,
    pub survey_id: Uuid,
    pub token_nonce: String,
    pub token_expires_at: DateTime<Utc>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<UserInput> for UserInputResponseDto {
    fn from(entity: UserInput) -> Self {
        Self {
            id: entity.id,
            survey_id: entity.survey_id,
            token_nonce: entity.token_nonce,
            token_expires_at: entity.token_expires_at,
            invite_token: entity.invite_token,
            partner_id: entity.partner_id,
            email: entity.email,
            nickname: entity.nickname,
            user_id: entity.user_id,
            wire_identity_key: entity.wire_identity_key,
            test_entry: entity.test_entry,
            state: entity.state,
            start_datetime: entity.start_datetime,
            end_datetime: entity.end_datetime,
            deadline: entity.deadline,
            is_session_answer: entity.is_session_answer,
            last_displayed_page_id: entity.last_displayed_page_id,
            scoring_percentage: entity.scoring_percentage,
            scoring_total: entity.scoring_total,
            scoring_success: entity.scoring_success,
            metadata: entity.metadata,
        }
    }
}

impl From<UserInput> for UserInputSummaryDto {
    fn from(entity: UserInput) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            survey_id: entity.survey_id,
            token_nonce: entity.token_nonce,
            token_expires_at: entity.token_expires_at,
            created_at,
        }
    }
}

impl From<CreateUserInputDto> for UserInput {
    fn from(dto: CreateUserInputDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            survey_id: dto.survey_id,
            token_nonce: dto.token_nonce,
            token_expires_at: dto.token_expires_at,
            invite_token: dto.invite_token,
            partner_id: dto.partner_id,
            email: dto.email,
            nickname: dto.nickname,
            user_id: dto.user_id,
            wire_identity_key: dto.wire_identity_key,
            test_entry: dto.test_entry,
            state: dto.state,
            start_datetime: dto.start_datetime,
            end_datetime: dto.end_datetime,
            deadline: dto.deadline,
            is_session_answer: dto.is_session_answer,
            last_displayed_page_id: dto.last_displayed_page_id,
            scoring_percentage: dto.scoring_percentage,
            scoring_total: dto.scoring_total,
            scoring_success: dto.scoring_success,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&UserInput> for UserInputResponseDto {
    fn from(entity: &UserInput) -> Self {
        Self {
            id: entity.id.clone(),
            survey_id: entity.survey_id.clone(),
            token_nonce: entity.token_nonce.clone(),
            token_expires_at: entity.token_expires_at.clone(),
            invite_token: entity.invite_token.clone(),
            partner_id: entity.partner_id.clone(),
            email: entity.email.clone(),
            nickname: entity.nickname.clone(),
            user_id: entity.user_id.clone(),
            wire_identity_key: entity.wire_identity_key.clone(),
            test_entry: entity.test_entry.clone(),
            state: entity.state.clone(),
            start_datetime: entity.start_datetime.clone(),
            end_datetime: entity.end_datetime.clone(),
            deadline: entity.deadline.clone(),
            is_session_answer: entity.is_session_answer.clone(),
            last_displayed_page_id: entity.last_displayed_page_id.clone(),
            scoring_percentage: entity.scoring_percentage.clone(),
            scoring_total: entity.scoring_total.clone(),
            scoring_success: entity.scoring_success.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateUserInputDto> for UserInput {
    fn from_create_dto(dto: CreateUserInputDto) -> backbone_core::ServiceResult<Self> {
        Ok(UserInput::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateUserInputDto> for UserInput {
    fn apply_update(mut self, dto: UpdateUserInputDto) -> backbone_core::ServiceResult<Self> {
        self.survey_id = dto.survey_id;
        self.token_nonce = dto.token_nonce;
        self.token_expires_at = dto.token_expires_at;
        self.invite_token = dto.invite_token;
        self.partner_id = dto.partner_id;
        self.email = dto.email;
        self.nickname = dto.nickname;
        self.user_id = dto.user_id;
        self.wire_identity_key = dto.wire_identity_key;
        self.test_entry = dto.test_entry;
        self.state = dto.state;
        self.start_datetime = dto.start_datetime;
        self.end_datetime = dto.end_datetime;
        self.deadline = dto.deadline;
        self.is_session_answer = dto.is_session_answer;
        self.last_displayed_page_id = dto.last_displayed_page_id;
        self.scoring_percentage = dto.scoring_percentage;
        self.scoring_total = dto.scoring_total;
        self.scoring_success = dto.scoring_success;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to UserInput here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
