//! UserInputLine DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::UserInputLine;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::SurveyAnswerType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new UserInputLine
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateUserInputLineDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "user_input_id")]
    pub user_input_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "survey_id")]
    pub survey_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "question_id")]
    pub question_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "suggested_answer_id")]
    pub suggested_answer_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "matrix_row_id")]
    pub matrix_row_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub skipped: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "answer_type")]
    pub answer_type: Option<SurveyAnswerType>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "value_char_box")]
    pub value_char_box: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "value_text_box")]
    pub value_text_box: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "value_numerical_box")]
    pub value_numerical_box: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "value_scale")]
    pub value_scale: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "value_date")]
    pub value_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "value_datetime")]
    pub value_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "answer_score")]
    pub answer_score: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "answer_is_correct")]
    pub answer_is_correct: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "speed_seconds")]
    pub speed_seconds: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "answered_at")]
    pub answered_at: DateTime<Utc>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a UserInputLine
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateUserInputLineDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "user_input_id")]
    pub user_input_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "survey_id")]
    pub survey_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "question_id")]
    pub question_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "suggested_answer_id")]
    pub suggested_answer_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "matrix_row_id")]
    pub matrix_row_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub skipped: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "answer_type")]
    pub answer_type: Option<SurveyAnswerType>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "value_char_box")]
    pub value_char_box: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "value_text_box")]
    pub value_text_box: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "value_numerical_box")]
    pub value_numerical_box: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "value_scale")]
    pub value_scale: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "value_date")]
    pub value_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "value_datetime")]
    pub value_datetime: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "answer_score")]
    pub answer_score: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "answer_is_correct")]
    pub answer_is_correct: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "speed_seconds")]
    pub speed_seconds: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "answered_at")]
    pub answered_at: DateTime<Utc>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a UserInputLine
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchUserInputLineDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "user_input_id")]
    pub user_input_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "survey_id")]
    pub survey_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "question_id")]
    pub question_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "suggested_answer_id")]
    pub suggested_answer_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "matrix_row_id")]
    pub matrix_row_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub skipped: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "answer_type")]
    pub answer_type: Option<SurveyAnswerType>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "value_char_box")]
    pub value_char_box: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "value_text_box")]
    pub value_text_box: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "value_numerical_box")]
    pub value_numerical_box: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "value_scale")]
    pub value_scale: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "value_date")]
    pub value_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "value_datetime")]
    pub value_datetime: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "answer_score")]
    pub answer_score: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "answer_is_correct")]
    pub answer_is_correct: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "speed_seconds")]
    pub speed_seconds: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "answered_at")]
    pub answered_at: Option<DateTime<Utc>>,
}

impl PatchUserInputLineDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.user_input_id.is_some() || self.survey_id.is_some() || self.question_id.is_some() || self.suggested_answer_id.is_some() || self.matrix_row_id.is_some() || self.skipped.is_some() || self.answer_type.is_some() || self.value_char_box.is_some() || self.value_text_box.is_some() || self.value_numerical_box.is_some() || self.value_scale.is_some() || self.value_date.is_some() || self.value_datetime.is_some() || self.answer_score.is_some() || self.answer_is_correct.is_some() || self.speed_seconds.is_some() || self.answered_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for UserInputLine entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct UserInputLineResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub user_input_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub survey_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub question_id: Uuid,
    pub suggested_answer_id: Option<Uuid>,
    pub matrix_row_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub skipped: bool,
    pub answer_type: Option<SurveyAnswerType>,
    pub value_char_box: Option<String>,
    pub value_text_box: Option<String>,
    pub value_numerical_box: Option<f64>,
    pub value_scale: Option<i32>,
    pub value_date: Option<NaiveDate>,
    pub value_datetime: Option<DateTime<Utc>>,
    pub answer_score: Option<f64>,
    pub answer_is_correct: Option<bool>,
    pub speed_seconds: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub answered_at: DateTime<Utc>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for UserInputLine entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct UserInputLineListResponseDto {
    /// List of items
    pub items: Vec<UserInputLineResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl UserInputLineListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<UserInputLineResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct UserInputLineSummaryDto {
    pub id: Uuid,
    pub user_input_id: Uuid,
    pub survey_id: Uuid,
    pub question_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<UserInputLine> for UserInputLineResponseDto {
    fn from(entity: UserInputLine) -> Self {
        Self {
            id: entity.id,
            user_input_id: entity.user_input_id,
            survey_id: entity.survey_id,
            question_id: entity.question_id,
            suggested_answer_id: entity.suggested_answer_id,
            matrix_row_id: entity.matrix_row_id,
            skipped: entity.skipped,
            answer_type: entity.answer_type,
            value_char_box: entity.value_char_box,
            value_text_box: entity.value_text_box,
            value_numerical_box: entity.value_numerical_box,
            value_scale: entity.value_scale,
            value_date: entity.value_date,
            value_datetime: entity.value_datetime,
            answer_score: entity.answer_score,
            answer_is_correct: entity.answer_is_correct,
            speed_seconds: entity.speed_seconds,
            answered_at: entity.answered_at,
            metadata: entity.metadata,
        }
    }
}

impl From<UserInputLine> for UserInputLineSummaryDto {
    fn from(entity: UserInputLine) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            user_input_id: entity.user_input_id,
            survey_id: entity.survey_id,
            question_id: entity.question_id,
            created_at,
        }
    }
}

impl From<CreateUserInputLineDto> for UserInputLine {
    fn from(dto: CreateUserInputLineDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            user_input_id: dto.user_input_id,
            survey_id: dto.survey_id,
            question_id: dto.question_id,
            suggested_answer_id: dto.suggested_answer_id,
            matrix_row_id: dto.matrix_row_id,
            skipped: dto.skipped,
            answer_type: dto.answer_type,
            value_char_box: dto.value_char_box,
            value_text_box: dto.value_text_box,
            value_numerical_box: dto.value_numerical_box,
            value_scale: dto.value_scale,
            value_date: dto.value_date,
            value_datetime: dto.value_datetime,
            answer_score: dto.answer_score,
            answer_is_correct: dto.answer_is_correct,
            speed_seconds: dto.speed_seconds,
            answered_at: dto.answered_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&UserInputLine> for UserInputLineResponseDto {
    fn from(entity: &UserInputLine) -> Self {
        Self {
            id: entity.id.clone(),
            user_input_id: entity.user_input_id.clone(),
            survey_id: entity.survey_id.clone(),
            question_id: entity.question_id.clone(),
            suggested_answer_id: entity.suggested_answer_id.clone(),
            matrix_row_id: entity.matrix_row_id.clone(),
            skipped: entity.skipped.clone(),
            answer_type: entity.answer_type.clone(),
            value_char_box: entity.value_char_box.clone(),
            value_text_box: entity.value_text_box.clone(),
            value_numerical_box: entity.value_numerical_box.clone(),
            value_scale: entity.value_scale.clone(),
            value_date: entity.value_date.clone(),
            value_datetime: entity.value_datetime.clone(),
            answer_score: entity.answer_score.clone(),
            answer_is_correct: entity.answer_is_correct.clone(),
            speed_seconds: entity.speed_seconds.clone(),
            answered_at: entity.answered_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateUserInputLineDto> for UserInputLine {
    fn from_create_dto(dto: CreateUserInputLineDto) -> backbone_core::ServiceResult<Self> {
        Ok(UserInputLine::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateUserInputLineDto> for UserInputLine {
    fn apply_update(mut self, dto: UpdateUserInputLineDto) -> backbone_core::ServiceResult<Self> {
        self.user_input_id = dto.user_input_id;
        self.survey_id = dto.survey_id;
        self.question_id = dto.question_id;
        self.suggested_answer_id = dto.suggested_answer_id;
        self.matrix_row_id = dto.matrix_row_id;
        self.skipped = dto.skipped;
        self.answer_type = dto.answer_type;
        self.value_char_box = dto.value_char_box;
        self.value_text_box = dto.value_text_box;
        self.value_numerical_box = dto.value_numerical_box;
        self.value_scale = dto.value_scale;
        self.value_date = dto.value_date;
        self.value_datetime = dto.value_datetime;
        self.answer_score = dto.answer_score;
        self.answer_is_correct = dto.answer_is_correct;
        self.speed_seconds = dto.speed_seconds;
        self.answered_at = dto.answered_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to UserInputLine here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
