//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod question_specification;
pub mod question_answer_specification;
pub mod survey_question_triggering_answer_specification;
pub mod survey_specification;
pub mod survey_survey_restrict_user_specification;
pub mod survey_survey_lang_specification;
pub mod user_input_specification;
pub mod user_input_line_specification;
pub mod survey_user_input_predefined_question_specification;

// <<< CUSTOM
// END CUSTOM
