//! Application service for SurveyQuestionTriggeringAnswer entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `survey_question_triggering_answer_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateSurveyQuestionTriggeringAnswerDto, UpdateSurveyQuestionTriggeringAnswerDto};
use crate::domain::entity::SurveyQuestionTriggeringAnswer;
use crate::infrastructure::persistence::SurveyQuestionTriggeringAnswerRepository;

/// Application service for SurveyQuestionTriggeringAnswer entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `survey_question_triggering_answer_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct SurveyQuestionTriggeringAnswerServiceCustom {
///     inner: Arc<SurveyQuestionTriggeringAnswerService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type SurveyQuestionTriggeringAnswerService = GenericCrudService<
    SurveyQuestionTriggeringAnswer,
    CreateSurveyQuestionTriggeringAnswerDto,
    UpdateSurveyQuestionTriggeringAnswerDto,
    SurveyQuestionTriggeringAnswerRepository,
>;

// <<< CUSTOM
// END CUSTOM
