//! Application service for SurveyUserInputPredefinedQuestion entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `survey_user_input_predefined_question_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateSurveyUserInputPredefinedQuestionDto, UpdateSurveyUserInputPredefinedQuestionDto};
use crate::domain::entity::SurveyUserInputPredefinedQuestion;
use crate::infrastructure::persistence::SurveyUserInputPredefinedQuestionRepository;

/// Application service for SurveyUserInputPredefinedQuestion entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `survey_user_input_predefined_question_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct SurveyUserInputPredefinedQuestionServiceCustom {
///     inner: Arc<SurveyUserInputPredefinedQuestionService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type SurveyUserInputPredefinedQuestionService = GenericCrudService<
    SurveyUserInputPredefinedQuestion,
    CreateSurveyUserInputPredefinedQuestionDto,
    UpdateSurveyUserInputPredefinedQuestionDto,
    SurveyUserInputPredefinedQuestionRepository,
>;

// <<< CUSTOM
// END CUSTOM
