//! Application service for UserInput entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `user_input_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateUserInputDto, UpdateUserInputDto};
use crate::domain::entity::UserInput;
use crate::infrastructure::persistence::UserInputRepository;

/// Application service for UserInput entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `user_input_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct UserInputServiceCustom {
///     inner: Arc<UserInputService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type UserInputService = GenericCrudService<
    UserInput,
    CreateUserInputDto,
    UpdateUserInputDto,
    UserInputRepository,
>;

// <<< CUSTOM
// END CUSTOM
