-- QuestionAnswer Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the survey.survey_question_answers table.
-- Customize this file to add your initial data.

-- INSERT INTO survey.survey_question_answers (
--     id,
--     question_id,
--     matrix_question_id,
--     sequence,
--     value,
--     value_image,
--     value_image_filename,
--     is_correct,
--     answer_score,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO survey.survey_question_answers (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

