-- SurveySurveyLang Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the survey.survey_survey_langs table.
-- Customize this file to add your initial data.

-- INSERT INTO survey.survey_survey_langs (
--     id,
--     survey_id,
--     lang_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO survey.survey_survey_langs (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

