-- SurveyUserInputPredefinedQuestion Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the survey.survey_user_input_predefined_questions table.
-- Customize this file to add your initial data.

-- INSERT INTO survey.survey_user_input_predefined_questions (
--     id,
--     user_input_id,
--     question_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO survey.survey_user_input_predefined_questions (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

