-- UserInputLine Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the survey.survey_user_input_lines table.
-- Customize this file to add your initial data.

-- INSERT INTO survey.survey_user_input_lines (
--     id,
--     user_input_id,
--     survey_id,
--     question_id,
--     suggested_answer_id,
--     matrix_row_id,
--     skipped,
--     answer_type,
--     value_char_box,
--     value_text_box,
--     value_numerical_box,
--     value_scale,
--     value_date,
--     value_datetime,
--     answer_score,
--     answer_is_correct,
--     speed_seconds,
--     answered_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO survey.survey_user_input_lines (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

