-- UserInput Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the survey.survey_user_inputs table.
-- Customize this file to add your initial data.

-- INSERT INTO survey.survey_user_inputs (
--     id,
--     survey_id,
--     token_nonce,
--     token_expires_at,
--     invite_token,
--     partner_id,
--     email,
--     nickname,
--     user_id,
--     wire_identity_key,
--     test_entry,
--     state,
--     start_datetime,
--     end_datetime,
--     deadline,
--     is_session_answer,
--     last_displayed_page_id,
--     scoring_percentage,
--     scoring_total,
--     scoring_success,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO survey.survey_user_inputs (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

