-- Migration: Create survey_user_inputs table
-- Generated by metaphor-schema

-- Create survey_input_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_input_state') THEN
        CREATE TYPE survey_input_state AS ENUM ('new', 'in_progress', 'done');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS survey;

CREATE TABLE IF NOT EXISTS survey.survey_user_inputs (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    survey_id UUID NOT NULL,
    token_nonce TEXT NOT NULL,
    token_expires_at TIMESTAMPTZ NOT NULL,
    invite_token TEXT,
    partner_id UUID,
    email TEXT,
    nickname TEXT,
    user_id UUID,
    wire_identity_key TEXT,
    test_entry BOOLEAN NOT NULL DEFAULT FALSE,
    state survey_input_state NOT NULL DEFAULT 'new',
    start_datetime TIMESTAMPTZ,
    end_datetime TIMESTAMPTZ,
    deadline TIMESTAMPTZ,
    is_session_answer BOOLEAN NOT NULL DEFAULT FALSE,
    last_displayed_page_id UUID,
    scoring_percentage DOUBLE PRECISION NOT NULL DEFAULT 0,
    scoring_total DOUBLE PRECISION NOT NULL DEFAULT 0,
    scoring_success BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_survey_user_inputs_survey_id_invite_token ON survey.survey_user_inputs (survey_id, invite_token);

CREATE INDEX IF NOT EXISTS idx_survey_user_inputs_survey_id_state ON survey.survey_user_inputs (survey_id, state);

CREATE INDEX IF NOT EXISTS idx_survey_user_inputs_survey_id_partner_id ON survey.survey_user_inputs (survey_id, partner_id);

CREATE INDEX IF NOT EXISTS idx_survey_user_inputs_survey_id_email ON survey.survey_user_inputs (survey_id, email);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_survey_user_inputs_metadata_gin ON survey.survey_user_inputs USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_survey_user_inputs_metadata_deleted_at ON survey.survey_user_inputs ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_survey_user_inputs_metadata_created_at ON survey.survey_user_inputs ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_survey_user_inputs_metadata_updated_at ON survey.survey_user_inputs ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION survey.survey_user_inputs_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS survey_user_inputs_insert_audit ON survey.survey_user_inputs;
CREATE TRIGGER survey_user_inputs_insert_audit BEFORE INSERT ON survey.survey_user_inputs
    FOR EACH ROW EXECUTE FUNCTION survey.survey_user_inputs_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS survey_user_inputs_update_audit ON survey.survey_user_inputs;
CREATE TRIGGER survey_user_inputs_update_audit BEFORE UPDATE ON survey.survey_user_inputs
    FOR EACH ROW EXECUTE FUNCTION survey.survey_user_inputs_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE survey.survey_user_inputs ADD CONSTRAINT fk_survey_user_inputs_survey_id FOREIGN KEY (survey_id) REFERENCES survey.survey_surveys (id) ON DELETE CASCADE;
