-- Migration: Create survey_questions table
-- Generated by metaphor-schema

-- Create survey_question_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_question_type') THEN
        CREATE TYPE survey_question_type AS ENUM ('simple_choice', 'multiple_choice', 'text_box', 'char_box', 'numerical_box', 'scale', 'date', 'datetime', 'matrix');
    END IF;
END
$$;

-- Create survey_matrix_subtype enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_matrix_subtype') THEN
        CREATE TYPE survey_matrix_subtype AS ENUM ('simple', 'multiple');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS survey;

CREATE TABLE IF NOT EXISTS survey.survey_questions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    survey_id UUID NOT NULL,
    sequence INTEGER NOT NULL DEFAULT 10,
    is_page BOOLEAN NOT NULL DEFAULT FALSE,
    question_type survey_question_type,
    title TEXT NOT NULL,
    description TEXT,
    question_placeholder TEXT,
    background_image TEXT,
    random_questions_count INTEGER NOT NULL DEFAULT 1,
    is_scored_question BOOLEAN NOT NULL DEFAULT FALSE,
    answer_numerical_box DOUBLE PRECISION,
    answer_date DATE,
    answer_datetime TIMESTAMPTZ,
    answer_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    save_as_email BOOLEAN NOT NULL DEFAULT FALSE,
    save_as_nickname BOOLEAN NOT NULL DEFAULT FALSE,
    matrix_subtype survey_matrix_subtype NOT NULL DEFAULT 'simple',
    scale_min INTEGER NOT NULL DEFAULT 0,
    scale_max INTEGER NOT NULL DEFAULT 10,
    scale_min_label TEXT,
    scale_mid_label TEXT,
    scale_max_label TEXT,
    is_time_limited BOOLEAN NOT NULL DEFAULT FALSE,
    time_limit INTEGER,
    is_time_customized BOOLEAN NOT NULL DEFAULT FALSE,
    comments_allowed BOOLEAN NOT NULL DEFAULT FALSE,
    comments_message TEXT,
    comment_count_as_answer BOOLEAN NOT NULL DEFAULT FALSE,
    validation_required BOOLEAN NOT NULL DEFAULT FALSE,
    validation_email BOOLEAN NOT NULL DEFAULT FALSE,
    validation_length_min INTEGER NOT NULL DEFAULT 0,
    validation_length_max INTEGER NOT NULL DEFAULT 0,
    validation_min_float_value DOUBLE PRECISION,
    validation_max_float_value DOUBLE PRECISION,
    validation_min_date DATE,
    validation_max_date DATE,
    validation_min_datetime TIMESTAMPTZ,
    validation_max_datetime TIMESTAMPTZ,
    validation_error_msg TEXT,
    constr_error_msg TEXT,
    constr_mandatory BOOLEAN NOT NULL DEFAULT FALSE,
    page_id UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_survey_questions_survey_id_sequence ON survey.survey_questions (survey_id, sequence);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_survey_questions_metadata_gin ON survey.survey_questions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_survey_questions_metadata_deleted_at ON survey.survey_questions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_survey_questions_metadata_created_at ON survey.survey_questions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_survey_questions_metadata_updated_at ON survey.survey_questions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION survey.survey_questions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS survey_questions_insert_audit ON survey.survey_questions;
CREATE TRIGGER survey_questions_insert_audit BEFORE INSERT ON survey.survey_questions
    FOR EACH ROW EXECUTE FUNCTION survey.survey_questions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS survey_questions_update_audit ON survey.survey_questions;
CREATE TRIGGER survey_questions_update_audit BEFORE UPDATE ON survey.survey_questions
    FOR EACH ROW EXECUTE FUNCTION survey.survey_questions_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE survey.survey_questions ADD CONSTRAINT fk_survey_questions_survey_id FOREIGN KEY (survey_id) REFERENCES survey.survey_surveys (id) ON DELETE CASCADE;
