-- Migration: Create survey_survey_restrict_users table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS survey;

CREATE TABLE IF NOT EXISTS survey.survey_survey_restrict_users (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    survey_id UUID NOT NULL,
    user_id UUID NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_survey_survey_restrict_users_survey_id_user_id ON survey.survey_survey_restrict_users (survey_id, user_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_survey_survey_restrict_users_metadata_gin ON survey.survey_survey_restrict_users USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_survey_survey_restrict_users_metadata_deleted_at ON survey.survey_survey_restrict_users ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_survey_survey_restrict_users_metadata_created_at ON survey.survey_survey_restrict_users ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_survey_survey_restrict_users_metadata_updated_at ON survey.survey_survey_restrict_users ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION survey.survey_survey_restrict_users_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS survey_survey_restrict_users_insert_audit ON survey.survey_survey_restrict_users;
CREATE TRIGGER survey_survey_restrict_users_insert_audit BEFORE INSERT ON survey.survey_survey_restrict_users
    FOR EACH ROW EXECUTE FUNCTION survey.survey_survey_restrict_users_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS survey_survey_restrict_users_update_audit ON survey.survey_survey_restrict_users;
CREATE TRIGGER survey_survey_restrict_users_update_audit BEFORE UPDATE ON survey.survey_survey_restrict_users
    FOR EACH ROW EXECUTE FUNCTION survey.survey_survey_restrict_users_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE survey.survey_survey_restrict_users ADD CONSTRAINT fk_survey_survey_restrict_users_survey_id FOREIGN KEY (survey_id) REFERENCES survey.survey_surveys (id) ON DELETE CASCADE;
