-- Migration: Create survey_surveys table
-- Generated by metaphor-schema

-- Create survey_survey_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_survey_type') THEN
        CREATE TYPE survey_survey_type AS ENUM ('survey', 'live_session', 'assessment', 'custom');
    END IF;
END
$$;

-- Create survey_questions_layout enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_questions_layout') THEN
        CREATE TYPE survey_questions_layout AS ENUM ('page_per_question', 'page_per_section', 'one_page');
    END IF;
END
$$;

-- Create survey_questions_selection enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_questions_selection') THEN
        CREATE TYPE survey_questions_selection AS ENUM ('all', 'random');
    END IF;
END
$$;

-- Create survey_progression_mode enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_progression_mode') THEN
        CREATE TYPE survey_progression_mode AS ENUM ('percent', 'number');
    END IF;
END
$$;

-- Create survey_access_mode enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_access_mode') THEN
        CREATE TYPE survey_access_mode AS ENUM ('public', 'token');
    END IF;
END
$$;

-- Create survey_scoring_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_scoring_type') THEN
        CREATE TYPE survey_scoring_type AS ENUM ('no_scoring', 'scoring_with_answers_after_page', 'scoring_with_answers', 'scoring_without_answers');
    END IF;
END
$$;

-- Create survey_report_layout enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_report_layout') THEN
        CREATE TYPE survey_report_layout AS ENUM ('modern_purple', 'modern_blue', 'modern_gold', 'classic_purple', 'classic_blue', 'classic_gold');
    END IF;
END
$$;

-- Create survey_session_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_session_state') THEN
        CREATE TYPE survey_session_state AS ENUM ('ready', 'in_progress');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS survey;

CREATE TABLE IF NOT EXISTS survey.survey_surveys (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    survey_type survey_survey_type NOT NULL DEFAULT 'custom',
    title TEXT NOT NULL,
    description TEXT,
    description_done TEXT,
    background_image TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    user_id UUID,
    access_token TEXT NOT NULL,
    questions_layout survey_questions_layout NOT NULL DEFAULT 'page_per_question',
    questions_selection survey_questions_selection NOT NULL DEFAULT 'all',
    progression_mode survey_progression_mode NOT NULL DEFAULT 'percent',
    access_mode survey_access_mode NOT NULL DEFAULT 'public',
    users_login_required BOOLEAN NOT NULL DEFAULT FALSE,
    users_can_go_back BOOLEAN NOT NULL DEFAULT FALSE,
    is_attempts_limited BOOLEAN NOT NULL DEFAULT FALSE,
    attempts_limit INTEGER NOT NULL DEFAULT 1,
    is_time_limited BOOLEAN NOT NULL DEFAULT FALSE,
    time_limit DOUBLE PRECISION NOT NULL DEFAULT 10,
    scoring_type survey_scoring_type NOT NULL DEFAULT 'no_scoring',
    scoring_success_min DOUBLE PRECISION NOT NULL DEFAULT 80,
    certification BOOLEAN NOT NULL DEFAULT FALSE,
    certification_mail_template_id UUID,
    certification_report_layout survey_report_layout NOT NULL DEFAULT 'modern_purple',
    certification_give_badge BOOLEAN NOT NULL DEFAULT FALSE,
    certification_badge_key TEXT,
    session_state survey_session_state,
    session_code TEXT,
    session_question_id UUID,
    session_start_time TIMESTAMPTZ,
    session_question_start_time TIMESTAMPTZ,
    session_speed_rating BOOLEAN NOT NULL DEFAULT FALSE,
    session_speed_rating_time_limit INTEGER,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_survey_surveys_access_token ON survey.survey_surveys (access_token);

CREATE UNIQUE INDEX IF NOT EXISTS idx_survey_surveys_session_code ON survey.survey_surveys (session_code) WHERE session_code IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_survey_surveys_certification_badge_key ON survey.survey_surveys (certification_badge_key) WHERE certification_badge_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_survey_surveys_active_survey_type ON survey.survey_surveys (active, survey_type);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_survey_surveys_metadata_gin ON survey.survey_surveys USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_survey_surveys_metadata_deleted_at ON survey.survey_surveys ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_survey_surveys_metadata_created_at ON survey.survey_surveys ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_survey_surveys_metadata_updated_at ON survey.survey_surveys ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION survey.survey_surveys_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS survey_surveys_insert_audit ON survey.survey_surveys;
CREATE TRIGGER survey_surveys_insert_audit BEFORE INSERT ON survey.survey_surveys
    FOR EACH ROW EXECUTE FUNCTION survey.survey_surveys_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS survey_surveys_update_audit ON survey.survey_surveys;
CREATE TRIGGER survey_surveys_update_audit BEFORE UPDATE ON survey.survey_surveys
    FOR EACH ROW EXECUTE FUNCTION survey.survey_surveys_audit_timestamp();
