-- Audit Triggers Migration for survey module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Question (survey.survey_questions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION survey.survey_questions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS survey_questions_insert_audit ON survey.survey_questions;
CREATE TRIGGER survey_questions_insert_audit BEFORE INSERT ON survey.survey_questions
    FOR EACH ROW EXECUTE FUNCTION survey.survey_questions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS survey_questions_update_audit ON survey.survey_questions;
CREATE TRIGGER survey_questions_update_audit BEFORE UPDATE ON survey.survey_questions
    FOR EACH ROW EXECUTE FUNCTION survey.survey_questions_audit_timestamp();

-- ==============================================================================
-- Table: QuestionAnswer (survey.survey_question_answers)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION survey.survey_question_answers_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS survey_question_answers_insert_audit ON survey.survey_question_answers;
CREATE TRIGGER survey_question_answers_insert_audit BEFORE INSERT ON survey.survey_question_answers
    FOR EACH ROW EXECUTE FUNCTION survey.survey_question_answers_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS survey_question_answers_update_audit ON survey.survey_question_answers;
CREATE TRIGGER survey_question_answers_update_audit BEFORE UPDATE ON survey.survey_question_answers
    FOR EACH ROW EXECUTE FUNCTION survey.survey_question_answers_audit_timestamp();

-- ==============================================================================
-- Table: SurveyQuestionTriggeringAnswer (survey.survey_question_triggering_answers)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION survey.survey_question_triggering_answers_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS survey_question_triggering_answers_insert_audit ON survey.survey_question_triggering_answers;
CREATE TRIGGER survey_question_triggering_answers_insert_audit BEFORE INSERT ON survey.survey_question_triggering_answers
    FOR EACH ROW EXECUTE FUNCTION survey.survey_question_triggering_answers_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS survey_question_triggering_answers_update_audit ON survey.survey_question_triggering_answers;
CREATE TRIGGER survey_question_triggering_answers_update_audit BEFORE UPDATE ON survey.survey_question_triggering_answers
    FOR EACH ROW EXECUTE FUNCTION survey.survey_question_triggering_answers_audit_timestamp();

-- ==============================================================================
-- Table: Survey (survey.survey_surveys)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION survey.survey_surveys_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS survey_surveys_insert_audit ON survey.survey_surveys;
CREATE TRIGGER survey_surveys_insert_audit BEFORE INSERT ON survey.survey_surveys
    FOR EACH ROW EXECUTE FUNCTION survey.survey_surveys_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS survey_surveys_update_audit ON survey.survey_surveys;
CREATE TRIGGER survey_surveys_update_audit BEFORE UPDATE ON survey.survey_surveys
    FOR EACH ROW EXECUTE FUNCTION survey.survey_surveys_audit_timestamp();

-- ==============================================================================
-- Table: SurveySurveyRestrictUser (survey.survey_survey_restrict_users)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION survey.survey_survey_restrict_users_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS survey_survey_restrict_users_insert_audit ON survey.survey_survey_restrict_users;
CREATE TRIGGER survey_survey_restrict_users_insert_audit BEFORE INSERT ON survey.survey_survey_restrict_users
    FOR EACH ROW EXECUTE FUNCTION survey.survey_survey_restrict_users_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS survey_survey_restrict_users_update_audit ON survey.survey_survey_restrict_users;
CREATE TRIGGER survey_survey_restrict_users_update_audit BEFORE UPDATE ON survey.survey_survey_restrict_users
    FOR EACH ROW EXECUTE FUNCTION survey.survey_survey_restrict_users_audit_timestamp();

-- ==============================================================================
-- Table: SurveySurveyLang (survey.survey_survey_langs)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION survey.survey_survey_langs_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS survey_survey_langs_insert_audit ON survey.survey_survey_langs;
CREATE TRIGGER survey_survey_langs_insert_audit BEFORE INSERT ON survey.survey_survey_langs
    FOR EACH ROW EXECUTE FUNCTION survey.survey_survey_langs_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS survey_survey_langs_update_audit ON survey.survey_survey_langs;
CREATE TRIGGER survey_survey_langs_update_audit BEFORE UPDATE ON survey.survey_survey_langs
    FOR EACH ROW EXECUTE FUNCTION survey.survey_survey_langs_audit_timestamp();

-- ==============================================================================
-- Table: UserInput (survey.survey_user_inputs)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION survey.survey_user_inputs_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS survey_user_inputs_insert_audit ON survey.survey_user_inputs;
CREATE TRIGGER survey_user_inputs_insert_audit BEFORE INSERT ON survey.survey_user_inputs
    FOR EACH ROW EXECUTE FUNCTION survey.survey_user_inputs_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS survey_user_inputs_update_audit ON survey.survey_user_inputs;
CREATE TRIGGER survey_user_inputs_update_audit BEFORE UPDATE ON survey.survey_user_inputs
    FOR EACH ROW EXECUTE FUNCTION survey.survey_user_inputs_audit_timestamp();

-- ==============================================================================
-- Table: UserInputLine (survey.survey_user_input_lines)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION survey.survey_user_input_lines_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS survey_user_input_lines_insert_audit ON survey.survey_user_input_lines;
CREATE TRIGGER survey_user_input_lines_insert_audit BEFORE INSERT ON survey.survey_user_input_lines
    FOR EACH ROW EXECUTE FUNCTION survey.survey_user_input_lines_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS survey_user_input_lines_update_audit ON survey.survey_user_input_lines;
CREATE TRIGGER survey_user_input_lines_update_audit BEFORE UPDATE ON survey.survey_user_input_lines
    FOR EACH ROW EXECUTE FUNCTION survey.survey_user_input_lines_audit_timestamp();

-- ==============================================================================
-- Table: SurveyUserInputPredefinedQuestion (survey.survey_user_input_predefined_questions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION survey.survey_user_input_predefined_questions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS survey_user_input_predefined_questions_insert_audit ON survey.survey_user_input_predefined_questions;
CREATE TRIGGER survey_user_input_predefined_questions_insert_audit BEFORE INSERT ON survey.survey_user_input_predefined_questions
    FOR EACH ROW EXECUTE FUNCTION survey.survey_user_input_predefined_questions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS survey_user_input_predefined_questions_update_audit ON survey.survey_user_input_predefined_questions;
CREATE TRIGGER survey_user_input_predefined_questions_update_audit BEFORE UPDATE ON survey.survey_user_input_predefined_questions
    FOR EACH ROW EXECUTE FUNCTION survey.survey_user_input_predefined_questions_audit_timestamp();

