-- Enum types for survey module
-- Generated by metaphor-schema

-- Create survey_question_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_question_type') THEN
        CREATE TYPE survey_question_type AS ENUM ('simple_choice', 'multiple_choice', 'text_box', 'char_box', 'numerical_box', 'scale', 'date', 'datetime', 'matrix');
    END IF;
END
$$;

-- Create survey_matrix_subtype enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_matrix_subtype') THEN
        CREATE TYPE survey_matrix_subtype AS ENUM ('simple', 'multiple');
    END IF;
END
$$;

-- Create survey_survey_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_survey_type') THEN
        CREATE TYPE survey_survey_type AS ENUM ('survey', 'live_session', 'assessment', 'custom');
    END IF;
END
$$;

-- Create survey_access_mode enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_access_mode') THEN
        CREATE TYPE survey_access_mode AS ENUM ('public', 'token');
    END IF;
END
$$;

-- Create survey_scoring_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_scoring_type') THEN
        CREATE TYPE survey_scoring_type AS ENUM ('no_scoring', 'scoring_with_answers_after_page', 'scoring_with_answers', 'scoring_without_answers');
    END IF;
END
$$;

-- Create survey_session_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_session_state') THEN
        CREATE TYPE survey_session_state AS ENUM ('ready', 'in_progress');
    END IF;
END
$$;

-- Create survey_questions_layout enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_questions_layout') THEN
        CREATE TYPE survey_questions_layout AS ENUM ('page_per_question', 'page_per_section', 'one_page');
    END IF;
END
$$;

-- Create survey_questions_selection enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_questions_selection') THEN
        CREATE TYPE survey_questions_selection AS ENUM ('all', 'random');
    END IF;
END
$$;

-- Create survey_report_layout enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_report_layout') THEN
        CREATE TYPE survey_report_layout AS ENUM ('modern_purple', 'modern_blue', 'modern_gold', 'classic_purple', 'classic_blue', 'classic_gold');
    END IF;
END
$$;

-- Create survey_progression_mode enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_progression_mode') THEN
        CREATE TYPE survey_progression_mode AS ENUM ('percent', 'number');
    END IF;
END
$$;

-- Create survey_invite_existing_mode enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_invite_existing_mode') THEN
        CREATE TYPE survey_invite_existing_mode AS ENUM ('new', 'resend');
    END IF;
END
$$;

-- Create survey_input_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_input_state') THEN
        CREATE TYPE survey_input_state AS ENUM ('new', 'in_progress', 'done');
    END IF;
END
$$;

-- Create survey_answer_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_answer_type') THEN
        CREATE TYPE survey_answer_type AS ENUM ('text_box', 'char_box', 'numerical_box', 'scale', 'date', 'datetime', 'suggestion');
    END IF;
END
$$;

