-- Migration: Create survey_user_input_predefined_questions table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS survey;

CREATE TABLE IF NOT EXISTS survey.survey_user_input_predefined_questions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_input_id UUID NOT NULL,
    question_id UUID NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_survey_user_input_predefined_questions_user_input_id_question_id ON survey.survey_user_input_predefined_questions (user_input_id, question_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_survey_user_input_predefined_questions_metadata_gin ON survey.survey_user_input_predefined_questions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_survey_user_input_predefined_questions_metadata_deleted_at ON survey.survey_user_input_predefined_questions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_survey_user_input_predefined_questions_metadata_created_at ON survey.survey_user_input_predefined_questions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_survey_user_input_predefined_questions_metadata_updated_at ON survey.survey_user_input_predefined_questions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION survey.survey_user_input_predefined_questions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS survey_user_input_predefined_questions_insert_audit ON survey.survey_user_input_predefined_questions;
CREATE TRIGGER survey_user_input_predefined_questions_insert_audit BEFORE INSERT ON survey.survey_user_input_predefined_questions
    FOR EACH ROW EXECUTE FUNCTION survey.survey_user_input_predefined_questions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS survey_user_input_predefined_questions_update_audit ON survey.survey_user_input_predefined_questions;
CREATE TRIGGER survey_user_input_predefined_questions_update_audit BEFORE UPDATE ON survey.survey_user_input_predefined_questions
    FOR EACH ROW EXECUTE FUNCTION survey.survey_user_input_predefined_questions_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE survey.survey_user_input_predefined_questions ADD CONSTRAINT fk_survey_user_input_predefined_questions_user_input_id FOREIGN KEY (user_input_id) REFERENCES survey.survey_user_inputs (id) ON DELETE CASCADE;
ALTER TABLE survey.survey_user_input_predefined_questions ADD CONSTRAINT fk_survey_user_input_predefined_questions_question_id FOREIGN KEY (question_id) REFERENCES survey.survey_questions (id) ON DELETE CASCADE;
