-- Migration: Create survey_user_input_lines table
-- Generated by metaphor-schema

-- Create survey_answer_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'survey_answer_type') THEN
        CREATE TYPE survey_answer_type AS ENUM ('text_box', 'char_box', 'numerical_box', 'scale', 'date', 'datetime', 'suggestion');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS survey;

CREATE TABLE IF NOT EXISTS survey.survey_user_input_lines (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_input_id UUID NOT NULL,
    survey_id UUID NOT NULL,
    question_id UUID NOT NULL,
    suggested_answer_id UUID,
    matrix_row_id UUID,
    skipped BOOLEAN NOT NULL DEFAULT FALSE,
    answer_type survey_answer_type,
    value_char_box TEXT,
    value_text_box TEXT,
    value_numerical_box DOUBLE PRECISION,
    value_scale INTEGER,
    value_date DATE,
    value_datetime TIMESTAMPTZ,
    answer_score DOUBLE PRECISION,
    answer_is_correct BOOLEAN,
    speed_seconds INTEGER,
    answered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_survey_user_input_lines_user_input_id_question_id ON survey.survey_user_input_lines (user_input_id, question_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_survey_user_input_lines_metadata_gin ON survey.survey_user_input_lines USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_survey_user_input_lines_metadata_deleted_at ON survey.survey_user_input_lines ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_survey_user_input_lines_metadata_created_at ON survey.survey_user_input_lines ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_survey_user_input_lines_metadata_updated_at ON survey.survey_user_input_lines ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION survey.survey_user_input_lines_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS survey_user_input_lines_insert_audit ON survey.survey_user_input_lines;
CREATE TRIGGER survey_user_input_lines_insert_audit BEFORE INSERT ON survey.survey_user_input_lines
    FOR EACH ROW EXECUTE FUNCTION survey.survey_user_input_lines_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS survey_user_input_lines_update_audit ON survey.survey_user_input_lines;
CREATE TRIGGER survey_user_input_lines_update_audit BEFORE UPDATE ON survey.survey_user_input_lines
    FOR EACH ROW EXECUTE FUNCTION survey.survey_user_input_lines_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE survey.survey_user_input_lines ADD CONSTRAINT fk_survey_user_input_lines_user_input_id FOREIGN KEY (user_input_id) REFERENCES survey.survey_user_inputs (id) ON DELETE CASCADE;
ALTER TABLE survey.survey_user_input_lines ADD CONSTRAINT fk_survey_user_input_lines_question_id FOREIGN KEY (question_id) REFERENCES survey.survey_questions (id) ON DELETE CASCADE;
