//! Domain events for Question entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Question;

/// Domain events for Question — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Question>)` variant.
pub type QuestionEvent = CrudEvent<Question>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Question events.
pub type QuestionEventPublisher = Arc<dyn CrudEventPublisher<Question> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopQuestionEventPublisher = NoOpCrudEventPublisher<Question>;
