//! Event handler trait for QuestionAnswer events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::QuestionAnswerEvent;

/// Event handler for QuestionAnswer events.
/// Implement this trait to react to QuestionAnswer lifecycle events.
pub trait QuestionAnswerEventHandler: EventHandler<QuestionAnswerEvent> {}
