//! Domain events for QuestionAnswer entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::QuestionAnswer;

/// Domain events for QuestionAnswer — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<QuestionAnswer>)` variant.
pub type QuestionAnswerEvent = CrudEvent<QuestionAnswer>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for QuestionAnswer events.
pub type QuestionAnswerEventPublisher = Arc<dyn CrudEventPublisher<QuestionAnswer> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopQuestionAnswerEventPublisher = NoOpCrudEventPublisher<QuestionAnswer>;
