//! Event handler trait for SurveySurveyLang events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SurveySurveyLangEvent;

/// Event handler for SurveySurveyLang events.
/// Implement this trait to react to SurveySurveyLang lifecycle events.
pub trait SurveySurveyLangEventHandler: EventHandler<SurveySurveyLangEvent> {}
