//! Event handler trait for SurveyQuestionTriggeringAnswer events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SurveyQuestionTriggeringAnswerEvent;

/// Event handler for SurveyQuestionTriggeringAnswer events.
/// Implement this trait to react to SurveyQuestionTriggeringAnswer lifecycle events.
pub trait SurveyQuestionTriggeringAnswerEventHandler: EventHandler<SurveyQuestionTriggeringAnswerEvent> {}
