//! Event handler trait for SurveySurveyRestrictUser events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SurveySurveyRestrictUserEvent;

/// Event handler for SurveySurveyRestrictUser events.
/// Implement this trait to react to SurveySurveyRestrictUser lifecycle events.
pub trait SurveySurveyRestrictUserEventHandler: EventHandler<SurveySurveyRestrictUserEvent> {}
