//! Domain events for SurveyUserInputPredefinedQuestion entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::SurveyUserInputPredefinedQuestion;

/// Domain events for SurveyUserInputPredefinedQuestion — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<SurveyUserInputPredefinedQuestion>)` variant.
pub type SurveyUserInputPredefinedQuestionEvent = CrudEvent<SurveyUserInputPredefinedQuestion>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for SurveyUserInputPredefinedQuestion events.
pub type SurveyUserInputPredefinedQuestionEventPublisher = Arc<dyn CrudEventPublisher<SurveyUserInputPredefinedQuestion> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSurveyUserInputPredefinedQuestionEventPublisher = NoOpCrudEventPublisher<SurveyUserInputPredefinedQuestion>;
