//! Domain events for SurveySurveyLang entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::SurveySurveyLang;

/// Domain events for SurveySurveyLang — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<SurveySurveyLang>)` variant.
pub type SurveySurveyLangEvent = CrudEvent<SurveySurveyLang>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for SurveySurveyLang events.
pub type SurveySurveyLangEventPublisher = Arc<dyn CrudEventPublisher<SurveySurveyLang> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSurveySurveyLangEventPublisher = NoOpCrudEventPublisher<SurveySurveyLang>;
