//! Domain events for Survey entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Survey;

/// Domain events for Survey — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Survey>)` variant.
pub type SurveyEvent = CrudEvent<Survey>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Survey events.
pub type SurveyEventPublisher = Arc<dyn CrudEventPublisher<Survey> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSurveyEventPublisher = NoOpCrudEventPublisher<Survey>;
