//! Event handler trait for Survey events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SurveyEvent;

/// Event handler for Survey events.
/// Implement this trait to react to Survey lifecycle events.
pub trait SurveyEventHandler: EventHandler<SurveyEvent> {}
