//! Domain events for SurveySurveyRestrictUser entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::SurveySurveyRestrictUser;

/// Domain events for SurveySurveyRestrictUser — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<SurveySurveyRestrictUser>)` variant.
pub type SurveySurveyRestrictUserEvent = CrudEvent<SurveySurveyRestrictUser>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for SurveySurveyRestrictUser events.
pub type SurveySurveyRestrictUserEventPublisher = Arc<dyn CrudEventPublisher<SurveySurveyRestrictUser> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSurveySurveyRestrictUserEventPublisher = NoOpCrudEventPublisher<SurveySurveyRestrictUser>;
