//! Domain events for SurveyQuestionTriggeringAnswer entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::SurveyQuestionTriggeringAnswer;

/// Domain events for SurveyQuestionTriggeringAnswer — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<SurveyQuestionTriggeringAnswer>)` variant.
pub type SurveyQuestionTriggeringAnswerEvent = CrudEvent<SurveyQuestionTriggeringAnswer>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for SurveyQuestionTriggeringAnswer events.
pub type SurveyQuestionTriggeringAnswerEventPublisher = Arc<dyn CrudEventPublisher<SurveyQuestionTriggeringAnswer> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSurveyQuestionTriggeringAnswerEventPublisher = NoOpCrudEventPublisher<SurveyQuestionTriggeringAnswer>;
