//! Event handler trait for SurveyUserInputPredefinedQuestion events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SurveyUserInputPredefinedQuestionEvent;

/// Event handler for SurveyUserInputPredefinedQuestion events.
/// Implement this trait to react to SurveyUserInputPredefinedQuestion lifecycle events.
pub trait SurveyUserInputPredefinedQuestionEventHandler: EventHandler<SurveyUserInputPredefinedQuestionEvent> {}
