//! Event handler trait for UserInput events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::UserInputEvent;

/// Event handler for UserInput events.
/// Implement this trait to react to UserInput lifecycle events.
pub trait UserInputEventHandler: EventHandler<UserInputEvent> {}
