//! Domain events for UserInputLine entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::UserInputLine;

/// Domain events for UserInputLine — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<UserInputLine>)` variant.
pub type UserInputLineEvent = CrudEvent<UserInputLine>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for UserInputLine events.
pub type UserInputLineEventPublisher = Arc<dyn CrudEventPublisher<UserInputLine> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopUserInputLineEventPublisher = NoOpCrudEventPublisher<UserInputLine>;
