//! Domain events for UserInput entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::UserInput;

/// Domain events for UserInput — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<UserInput>)` variant.
pub type UserInputEvent = CrudEvent<UserInput>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for UserInput events.
pub type UserInputEventPublisher = Arc<dyn CrudEventPublisher<UserInput> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopUserInputEventPublisher = NoOpCrudEventPublisher<UserInput>;
