//! Database seeders for the survey module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides seed data for initial database setup.
//! Seeders can be run via the seeder binary or CLI.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

mod question_seeder;
mod question_answer_seeder;
mod survey_question_triggering_answer_seeder;
mod survey_seeder;
mod survey_survey_restrict_user_seeder;
mod survey_survey_lang_seeder;
mod user_input_seeder;
mod user_input_line_seeder;
mod survey_user_input_predefined_question_seeder;

pub use question_seeder::SeedQuestionSeeder;
pub use question_answer_seeder::SeedQuestionAnswerSeeder;
pub use survey_question_triggering_answer_seeder::SeedSurveyQuestionTriggeringAnswerSeeder;
pub use survey_seeder::SeedSurveySeeder;
pub use survey_survey_restrict_user_seeder::SeedSurveySurveyRestrictUserSeeder;
pub use survey_survey_lang_seeder::SeedSurveySurveyLangSeeder;
pub use user_input_seeder::SeedUserInputSeeder;
pub use user_input_line_seeder::SeedUserInputLineSeeder;
pub use survey_user_input_predefined_question_seeder::SeedSurveyUserInputPredefinedQuestionSeeder;

// ============================================================================
// SEEDER TRAIT
// ============================================================================

/// Trait for database seeders
#[async_trait]
pub trait Seeder {
    /// Get the name of this seeder
    fn name(&self) -> &'static str;

    /// Get the order in which this seeder should run
    fn order(&self) -> i32;

    /// Check if this seeder should run (e.g., check if data already exists)
    async fn should_run(&self, pool: &PgPool) -> Result<bool>;

    /// Run the seeder
    async fn run(&self, pool: &PgPool) -> Result<()>;

    /// Rollback the seeder (optional)
    async fn rollback(&self, _pool: &PgPool) -> Result<()> {
        Ok(())
    }
}

// ============================================================================
// SEEDER TYPE
// ============================================================================

/// Type of seeder
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SeederType {
    /// Reference data (required for application to function)
    Reference,
    /// Initial production data
    Production,
    /// Development/testing data
    Development,
    /// Test data (for automated tests)
    Test,
}

// ============================================================================
// CUSTOM SEEDERS
// ============================================================================

// <<< CUSTOM SEEDERS START >>>
// Add custom seeders here
// <<< CUSTOM SEEDERS END >>>
