//! SurveySurveyLang seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial SurveySurveyLang data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// SURVEYSURVEYLANG SEEDER
// ============================================================================

/// Seeder for survey_survey_lang
pub struct SeedSurveySurveyLangSeeder;

impl SeedSurveySurveyLangSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedSurveySurveyLangSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedSurveySurveyLangSeeder {
    fn name(&self) -> &'static str {
        "SeedSurveySurveyLangSeeder"
    }

    fn order(&self) -> i32 {
        6
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if survey.survey_survey_langs table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM survey.survey_survey_langs")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/survey_survey_lang_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM survey.survey_survey_langs")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
