//! UserInputLine seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial UserInputLine data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// USERINPUTLINE SEEDER
// ============================================================================

/// Seeder for user_input_line
pub struct SeedUserInputLineSeeder;

impl SeedUserInputLineSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedUserInputLineSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedUserInputLineSeeder {
    fn name(&self) -> &'static str {
        "SeedUserInputLineSeeder"
    }

    fn order(&self) -> i32 {
        8
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if survey.survey_user_input_lines table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM survey.survey_user_input_lines")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/user_input_line_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM survey.survey_user_input_lines")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
