//! Repository trait for QuestionAnswer aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the QuestionAnswer aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::QuestionAnswer;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct QuestionAnswerPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl QuestionAnswerPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct QuestionAnswerPaginatedResult {
    pub data: Vec<QuestionAnswer>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct QuestionAnswerFilter {
    pub question_id: Option<Uuid>,
    pub matrix_question_id: Option<Uuid>,
    pub value: Option<String>,
    pub value_image: Option<String>,
    pub value_image_filename: Option<String>,
    pub is_correct: Option<bool>,
}

impl QuestionAnswerFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.question_id.is_some() || self.matrix_question_id.is_some() || self.value.is_some() || self.value_image.is_some() || self.value_image_filename.is_some() || self.is_correct.is_some()
    }
}

/// Repository trait for QuestionAnswer aggregate
///
/// This trait defines the persistence contract for QuestionAnswer entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait QuestionAnswerRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new question_answer entity
    async fn save(&self, entity: &QuestionAnswer) -> Result<QuestionAnswer>;

    /// Find question_answer by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<QuestionAnswer>>;

    /// Find all question_answer entities
    async fn find_all(&self) -> Result<Vec<QuestionAnswer>>;

    /// Update question_answer by ID
    async fn update(&self, id: &str, entity: &QuestionAnswer) -> Result<Option<QuestionAnswer>>;

    /// Delete question_answer by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List question_answer with pagination
    async fn list(&self, params: QuestionAnswerPaginationParams) -> Result<QuestionAnswerPaginatedResult>;

    /// List question_answer with pagination and filters
    async fn list_with_filters(&self, params: QuestionAnswerPaginationParams, filters: QuestionAnswerFilter) -> Result<QuestionAnswerPaginatedResult>;

    /// Count all question_answer entities
    async fn count(&self) -> Result<u64>;

    /// Count question_answer entities matching filters
    async fn count_with_filters(&self, filters: QuestionAnswerFilter) -> Result<u64>;

    /// Check if question_answer exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete question_answer by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted question_answer by ID
    async fn restore(&self, id: &str) -> Result<Option<QuestionAnswer>>;

    /// List soft-deleted question_answer entities
    async fn list_deleted(&self, params: QuestionAnswerPaginationParams) -> Result<QuestionAnswerPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save question_answer entities
    async fn bulk_save(&self, entities: &[QuestionAnswer]) -> Result<Vec<QuestionAnswer>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
