//! Repository trait for Question aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Question aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Question, SurveyMatrixSubtype, SurveyQuestionType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct QuestionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl QuestionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct QuestionPaginatedResult {
    pub data: Vec<Question>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct QuestionFilter {
    pub survey_id: Option<Uuid>,
    pub is_page: Option<bool>,
    pub question_type: Option<SurveyQuestionType>,
    pub title: Option<String>,
    pub description: Option<String>,
    pub question_placeholder: Option<String>,
    pub background_image: Option<String>,
    pub is_scored_question: Option<bool>,
    pub save_as_email: Option<bool>,
    pub save_as_nickname: Option<bool>,
    pub matrix_subtype: Option<SurveyMatrixSubtype>,
    pub scale_min_label: Option<String>,
    pub scale_mid_label: Option<String>,
    pub scale_max_label: Option<String>,
    pub is_time_limited: Option<bool>,
    pub is_time_customized: Option<bool>,
    pub comments_allowed: Option<bool>,
    pub comments_message: Option<String>,
    pub comment_count_as_answer: Option<bool>,
    pub validation_required: Option<bool>,
    pub validation_email: Option<bool>,
    pub validation_error_msg: Option<String>,
    pub constr_error_msg: Option<String>,
    pub constr_mandatory: Option<bool>,
    pub page_id: Option<Uuid>,
}

impl QuestionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.survey_id.is_some() || self.is_page.is_some() || self.question_type.is_some() || self.title.is_some() || self.description.is_some() || self.question_placeholder.is_some() || self.background_image.is_some() || self.is_scored_question.is_some() || self.save_as_email.is_some() || self.save_as_nickname.is_some() || self.matrix_subtype.is_some() || self.scale_min_label.is_some() || self.scale_mid_label.is_some() || self.scale_max_label.is_some() || self.is_time_limited.is_some() || self.is_time_customized.is_some() || self.comments_allowed.is_some() || self.comments_message.is_some() || self.comment_count_as_answer.is_some() || self.validation_required.is_some() || self.validation_email.is_some() || self.validation_error_msg.is_some() || self.constr_error_msg.is_some() || self.constr_mandatory.is_some() || self.page_id.is_some()
    }
}

/// Repository trait for Question aggregate
///
/// This trait defines the persistence contract for Question entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait QuestionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new question entity
    async fn save(&self, entity: &Question) -> Result<Question>;

    /// Find question by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Question>>;

    /// Find all question entities
    async fn find_all(&self) -> Result<Vec<Question>>;

    /// Update question by ID
    async fn update(&self, id: &str, entity: &Question) -> Result<Option<Question>>;

    /// Delete question by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List question with pagination
    async fn list(&self, params: QuestionPaginationParams) -> Result<QuestionPaginatedResult>;

    /// List question with pagination and filters
    async fn list_with_filters(&self, params: QuestionPaginationParams, filters: QuestionFilter) -> Result<QuestionPaginatedResult>;

    /// Count all question entities
    async fn count(&self) -> Result<u64>;

    /// Count question entities matching filters
    async fn count_with_filters(&self, filters: QuestionFilter) -> Result<u64>;

    /// Check if question exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete question by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted question by ID
    async fn restore(&self, id: &str) -> Result<Option<Question>>;

    /// List soft-deleted question entities
    async fn list_deleted(&self, params: QuestionPaginationParams) -> Result<QuestionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save question entities
    async fn bulk_save(&self, entities: &[Question]) -> Result<Vec<Question>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
