//! Repository trait for SurveySurveyLang aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the SurveySurveyLang aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::SurveySurveyLang;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SurveySurveyLangPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SurveySurveyLangPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SurveySurveyLangPaginatedResult {
    pub data: Vec<SurveySurveyLang>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SurveySurveyLangFilter {
    pub survey_id: Option<Uuid>,
    pub lang_id: Option<Uuid>,
}

impl SurveySurveyLangFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.survey_id.is_some() || self.lang_id.is_some()
    }
}

/// Repository trait for SurveySurveyLang aggregate
///
/// This trait defines the persistence contract for SurveySurveyLang entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SurveySurveyLangRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new survey_survey_lang entity
    async fn save(&self, entity: &SurveySurveyLang) -> Result<SurveySurveyLang>;

    /// Find survey_survey_lang by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<SurveySurveyLang>>;

    /// Find all survey_survey_lang entities
    async fn find_all(&self) -> Result<Vec<SurveySurveyLang>>;

    /// Update survey_survey_lang by ID
    async fn update(&self, id: &str, entity: &SurveySurveyLang) -> Result<Option<SurveySurveyLang>>;

    /// Delete survey_survey_lang by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List survey_survey_lang with pagination
    async fn list(&self, params: SurveySurveyLangPaginationParams) -> Result<SurveySurveyLangPaginatedResult>;

    /// List survey_survey_lang with pagination and filters
    async fn list_with_filters(&self, params: SurveySurveyLangPaginationParams, filters: SurveySurveyLangFilter) -> Result<SurveySurveyLangPaginatedResult>;

    /// Count all survey_survey_lang entities
    async fn count(&self) -> Result<u64>;

    /// Count survey_survey_lang entities matching filters
    async fn count_with_filters(&self, filters: SurveySurveyLangFilter) -> Result<u64>;

    /// Check if survey_survey_lang exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete survey_survey_lang by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted survey_survey_lang by ID
    async fn restore(&self, id: &str) -> Result<Option<SurveySurveyLang>>;

    /// List soft-deleted survey_survey_lang entities
    async fn list_deleted(&self, params: SurveySurveyLangPaginationParams) -> Result<SurveySurveyLangPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save survey_survey_lang entities
    async fn bulk_save(&self, entities: &[SurveySurveyLang]) -> Result<Vec<SurveySurveyLang>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
