//! Repository trait for SurveyUserInputPredefinedQuestion aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the SurveyUserInputPredefinedQuestion aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::SurveyUserInputPredefinedQuestion;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SurveyUserInputPredefinedQuestionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SurveyUserInputPredefinedQuestionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SurveyUserInputPredefinedQuestionPaginatedResult {
    pub data: Vec<SurveyUserInputPredefinedQuestion>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SurveyUserInputPredefinedQuestionFilter {
    pub user_input_id: Option<Uuid>,
    pub question_id: Option<Uuid>,
}

impl SurveyUserInputPredefinedQuestionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.user_input_id.is_some() || self.question_id.is_some()
    }
}

/// Repository trait for SurveyUserInputPredefinedQuestion aggregate
///
/// This trait defines the persistence contract for SurveyUserInputPredefinedQuestion entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SurveyUserInputPredefinedQuestionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new survey_user_input_predefined_question entity
    async fn save(&self, entity: &SurveyUserInputPredefinedQuestion) -> Result<SurveyUserInputPredefinedQuestion>;

    /// Find survey_user_input_predefined_question by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<SurveyUserInputPredefinedQuestion>>;

    /// Find all survey_user_input_predefined_question entities
    async fn find_all(&self) -> Result<Vec<SurveyUserInputPredefinedQuestion>>;

    /// Update survey_user_input_predefined_question by ID
    async fn update(&self, id: &str, entity: &SurveyUserInputPredefinedQuestion) -> Result<Option<SurveyUserInputPredefinedQuestion>>;

    /// Delete survey_user_input_predefined_question by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List survey_user_input_predefined_question with pagination
    async fn list(&self, params: SurveyUserInputPredefinedQuestionPaginationParams) -> Result<SurveyUserInputPredefinedQuestionPaginatedResult>;

    /// List survey_user_input_predefined_question with pagination and filters
    async fn list_with_filters(&self, params: SurveyUserInputPredefinedQuestionPaginationParams, filters: SurveyUserInputPredefinedQuestionFilter) -> Result<SurveyUserInputPredefinedQuestionPaginatedResult>;

    /// Count all survey_user_input_predefined_question entities
    async fn count(&self) -> Result<u64>;

    /// Count survey_user_input_predefined_question entities matching filters
    async fn count_with_filters(&self, filters: SurveyUserInputPredefinedQuestionFilter) -> Result<u64>;

    /// Check if survey_user_input_predefined_question exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete survey_user_input_predefined_question by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted survey_user_input_predefined_question by ID
    async fn restore(&self, id: &str) -> Result<Option<SurveyUserInputPredefinedQuestion>>;

    /// List soft-deleted survey_user_input_predefined_question entities
    async fn list_deleted(&self, params: SurveyUserInputPredefinedQuestionPaginationParams) -> Result<SurveyUserInputPredefinedQuestionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save survey_user_input_predefined_question entities
    async fn bulk_save(&self, entities: &[SurveyUserInputPredefinedQuestion]) -> Result<Vec<SurveyUserInputPredefinedQuestion>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
