//! Repository trait for SurveyQuestionTriggeringAnswer aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the SurveyQuestionTriggeringAnswer aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::SurveyQuestionTriggeringAnswer;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SurveyQuestionTriggeringAnswerPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SurveyQuestionTriggeringAnswerPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SurveyQuestionTriggeringAnswerPaginatedResult {
    pub data: Vec<SurveyQuestionTriggeringAnswer>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SurveyQuestionTriggeringAnswerFilter {
    pub question_id: Option<Uuid>,
    pub suggested_answer_id: Option<Uuid>,
}

impl SurveyQuestionTriggeringAnswerFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.question_id.is_some() || self.suggested_answer_id.is_some()
    }
}

/// Repository trait for SurveyQuestionTriggeringAnswer aggregate
///
/// This trait defines the persistence contract for SurveyQuestionTriggeringAnswer entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SurveyQuestionTriggeringAnswerRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new survey_question_triggering_answer entity
    async fn save(&self, entity: &SurveyQuestionTriggeringAnswer) -> Result<SurveyQuestionTriggeringAnswer>;

    /// Find survey_question_triggering_answer by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<SurveyQuestionTriggeringAnswer>>;

    /// Find all survey_question_triggering_answer entities
    async fn find_all(&self) -> Result<Vec<SurveyQuestionTriggeringAnswer>>;

    /// Update survey_question_triggering_answer by ID
    async fn update(&self, id: &str, entity: &SurveyQuestionTriggeringAnswer) -> Result<Option<SurveyQuestionTriggeringAnswer>>;

    /// Delete survey_question_triggering_answer by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List survey_question_triggering_answer with pagination
    async fn list(&self, params: SurveyQuestionTriggeringAnswerPaginationParams) -> Result<SurveyQuestionTriggeringAnswerPaginatedResult>;

    /// List survey_question_triggering_answer with pagination and filters
    async fn list_with_filters(&self, params: SurveyQuestionTriggeringAnswerPaginationParams, filters: SurveyQuestionTriggeringAnswerFilter) -> Result<SurveyQuestionTriggeringAnswerPaginatedResult>;

    /// Count all survey_question_triggering_answer entities
    async fn count(&self) -> Result<u64>;

    /// Count survey_question_triggering_answer entities matching filters
    async fn count_with_filters(&self, filters: SurveyQuestionTriggeringAnswerFilter) -> Result<u64>;

    /// Check if survey_question_triggering_answer exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete survey_question_triggering_answer by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted survey_question_triggering_answer by ID
    async fn restore(&self, id: &str) -> Result<Option<SurveyQuestionTriggeringAnswer>>;

    /// List soft-deleted survey_question_triggering_answer entities
    async fn list_deleted(&self, params: SurveyQuestionTriggeringAnswerPaginationParams) -> Result<SurveyQuestionTriggeringAnswerPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save survey_question_triggering_answer entities
    async fn bulk_save(&self, entities: &[SurveyQuestionTriggeringAnswer]) -> Result<Vec<SurveyQuestionTriggeringAnswer>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
