//! Repository trait for SurveySurveyRestrictUser aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the SurveySurveyRestrictUser aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::SurveySurveyRestrictUser;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SurveySurveyRestrictUserPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SurveySurveyRestrictUserPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SurveySurveyRestrictUserPaginatedResult {
    pub data: Vec<SurveySurveyRestrictUser>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SurveySurveyRestrictUserFilter {
    pub survey_id: Option<Uuid>,
    pub user_id: Option<Uuid>,
}

impl SurveySurveyRestrictUserFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.survey_id.is_some() || self.user_id.is_some()
    }
}

/// Repository trait for SurveySurveyRestrictUser aggregate
///
/// This trait defines the persistence contract for SurveySurveyRestrictUser entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SurveySurveyRestrictUserRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new survey_survey_restrict_user entity
    async fn save(&self, entity: &SurveySurveyRestrictUser) -> Result<SurveySurveyRestrictUser>;

    /// Find survey_survey_restrict_user by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<SurveySurveyRestrictUser>>;

    /// Find all survey_survey_restrict_user entities
    async fn find_all(&self) -> Result<Vec<SurveySurveyRestrictUser>>;

    /// Update survey_survey_restrict_user by ID
    async fn update(&self, id: &str, entity: &SurveySurveyRestrictUser) -> Result<Option<SurveySurveyRestrictUser>>;

    /// Delete survey_survey_restrict_user by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List survey_survey_restrict_user with pagination
    async fn list(&self, params: SurveySurveyRestrictUserPaginationParams) -> Result<SurveySurveyRestrictUserPaginatedResult>;

    /// List survey_survey_restrict_user with pagination and filters
    async fn list_with_filters(&self, params: SurveySurveyRestrictUserPaginationParams, filters: SurveySurveyRestrictUserFilter) -> Result<SurveySurveyRestrictUserPaginatedResult>;

    /// Count all survey_survey_restrict_user entities
    async fn count(&self) -> Result<u64>;

    /// Count survey_survey_restrict_user entities matching filters
    async fn count_with_filters(&self, filters: SurveySurveyRestrictUserFilter) -> Result<u64>;

    /// Check if survey_survey_restrict_user exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete survey_survey_restrict_user by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted survey_survey_restrict_user by ID
    async fn restore(&self, id: &str) -> Result<Option<SurveySurveyRestrictUser>>;

    /// List soft-deleted survey_survey_restrict_user entities
    async fn list_deleted(&self, params: SurveySurveyRestrictUserPaginationParams) -> Result<SurveySurveyRestrictUserPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save survey_survey_restrict_user entities
    async fn bulk_save(&self, entities: &[SurveySurveyRestrictUser]) -> Result<Vec<SurveySurveyRestrictUser>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
