//! Repository trait for Survey aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Survey aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Survey, SurveyAccessMode, SurveyProgressionMode, SurveyQuestionsLayout, SurveyQuestionsSelection, SurveyReportLayout, SurveyScoringType, SurveySessionState, SurveySurveyType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SurveyPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SurveyPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SurveyPaginatedResult {
    pub data: Vec<Survey>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SurveyFilter {
    pub survey_type: Option<SurveySurveyType>,
    pub title: Option<String>,
    pub description: Option<String>,
    pub description_done: Option<String>,
    pub background_image: Option<String>,
    pub active: Option<bool>,
    pub user_id: Option<Uuid>,
    pub access_token: Option<String>,
    pub questions_layout: Option<SurveyQuestionsLayout>,
    pub questions_selection: Option<SurveyQuestionsSelection>,
    pub progression_mode: Option<SurveyProgressionMode>,
    pub access_mode: Option<SurveyAccessMode>,
    pub users_login_required: Option<bool>,
    pub users_can_go_back: Option<bool>,
    pub is_attempts_limited: Option<bool>,
    pub is_time_limited: Option<bool>,
    pub scoring_type: Option<SurveyScoringType>,
    pub certification: Option<bool>,
    pub certification_mail_template_id: Option<Uuid>,
    pub certification_report_layout: Option<SurveyReportLayout>,
    pub certification_give_badge: Option<bool>,
    pub certification_badge_key: Option<String>,
    pub session_state: Option<SurveySessionState>,
    pub session_code: Option<String>,
    pub session_question_id: Option<Uuid>,
    pub session_speed_rating: Option<bool>,
}

impl SurveyFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.survey_type.is_some() || self.title.is_some() || self.description.is_some() || self.description_done.is_some() || self.background_image.is_some() || self.active.is_some() || self.user_id.is_some() || self.access_token.is_some() || self.questions_layout.is_some() || self.questions_selection.is_some() || self.progression_mode.is_some() || self.access_mode.is_some() || self.users_login_required.is_some() || self.users_can_go_back.is_some() || self.is_attempts_limited.is_some() || self.is_time_limited.is_some() || self.scoring_type.is_some() || self.certification.is_some() || self.certification_mail_template_id.is_some() || self.certification_report_layout.is_some() || self.certification_give_badge.is_some() || self.certification_badge_key.is_some() || self.session_state.is_some() || self.session_code.is_some() || self.session_question_id.is_some() || self.session_speed_rating.is_some()
    }
}

/// Repository trait for Survey aggregate
///
/// This trait defines the persistence contract for Survey entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SurveyRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new survey entity
    async fn save(&self, entity: &Survey) -> Result<Survey>;

    /// Find survey by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Survey>>;

    /// Find all survey entities
    async fn find_all(&self) -> Result<Vec<Survey>>;

    /// Update survey by ID
    async fn update(&self, id: &str, entity: &Survey) -> Result<Option<Survey>>;

    /// Delete survey by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List survey with pagination
    async fn list(&self, params: SurveyPaginationParams) -> Result<SurveyPaginatedResult>;

    /// List survey with pagination and filters
    async fn list_with_filters(&self, params: SurveyPaginationParams, filters: SurveyFilter) -> Result<SurveyPaginatedResult>;

    /// Count all survey entities
    async fn count(&self) -> Result<u64>;

    /// Count survey entities matching filters
    async fn count_with_filters(&self, filters: SurveyFilter) -> Result<u64>;

    /// Check if survey exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete survey by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted survey by ID
    async fn restore(&self, id: &str) -> Result<Option<Survey>>;

    /// List soft-deleted survey entities
    async fn list_deleted(&self, params: SurveyPaginationParams) -> Result<SurveyPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save survey entities
    async fn bulk_save(&self, entities: &[Survey]) -> Result<Vec<Survey>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
