//! Repository trait for UserInput aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the UserInput aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{UserInput, SurveyInputState};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct UserInputPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl UserInputPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct UserInputPaginatedResult {
    pub data: Vec<UserInput>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct UserInputFilter {
    pub survey_id: Option<Uuid>,
    pub token_nonce: Option<String>,
    pub invite_token: Option<String>,
    pub partner_id: Option<Uuid>,
    pub email: Option<String>,
    pub nickname: Option<String>,
    pub user_id: Option<Uuid>,
    pub wire_identity_key: Option<String>,
    pub test_entry: Option<bool>,
    pub state: Option<SurveyInputState>,
    pub is_session_answer: Option<bool>,
    pub last_displayed_page_id: Option<Uuid>,
    pub scoring_success: Option<bool>,
}

impl UserInputFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.survey_id.is_some() || self.token_nonce.is_some() || self.invite_token.is_some() || self.partner_id.is_some() || self.email.is_some() || self.nickname.is_some() || self.user_id.is_some() || self.wire_identity_key.is_some() || self.test_entry.is_some() || self.state.is_some() || self.is_session_answer.is_some() || self.last_displayed_page_id.is_some() || self.scoring_success.is_some()
    }
}

/// Repository trait for UserInput aggregate
///
/// This trait defines the persistence contract for UserInput entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait UserInputRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new user_input entity
    async fn save(&self, entity: &UserInput) -> Result<UserInput>;

    /// Find user_input by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<UserInput>>;

    /// Find all user_input entities
    async fn find_all(&self) -> Result<Vec<UserInput>>;

    /// Update user_input by ID
    async fn update(&self, id: &str, entity: &UserInput) -> Result<Option<UserInput>>;

    /// Delete user_input by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List user_input with pagination
    async fn list(&self, params: UserInputPaginationParams) -> Result<UserInputPaginatedResult>;

    /// List user_input with pagination and filters
    async fn list_with_filters(&self, params: UserInputPaginationParams, filters: UserInputFilter) -> Result<UserInputPaginatedResult>;

    /// Count all user_input entities
    async fn count(&self) -> Result<u64>;

    /// Count user_input entities matching filters
    async fn count_with_filters(&self, filters: UserInputFilter) -> Result<u64>;

    /// Check if user_input exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete user_input by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted user_input by ID
    async fn restore(&self, id: &str) -> Result<Option<UserInput>>;

    /// List soft-deleted user_input entities
    async fn list_deleted(&self, params: UserInputPaginationParams) -> Result<UserInputPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save user_input entities
    async fn bulk_save(&self, entities: &[UserInput]) -> Result<Vec<UserInput>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
