//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod question_repository;
mod question_answer_repository;
mod survey_question_triggering_answer_repository;
mod survey_repository;
mod survey_survey_restrict_user_repository;
mod survey_survey_lang_repository;
mod user_input_repository;
mod user_input_line_repository;
mod survey_user_input_predefined_question_repository;

// Custom persistence modules
// <<< CUSTOM
pub(crate) mod attempt_repository;
pub(crate) mod scoring_repository;
pub(crate) mod survey_session_repository;
// END CUSTOM

// Re-exports
pub use question_repository::QuestionRepository;
pub use question_answer_repository::QuestionAnswerRepository;
pub use survey_question_triggering_answer_repository::SurveyQuestionTriggeringAnswerRepository;
pub use survey_repository::SurveyRepository;
pub use survey_survey_restrict_user_repository::SurveySurveyRestrictUserRepository;
pub use survey_survey_lang_repository::SurveySurveyLangRepository;
pub use user_input_repository::UserInputRepository;
pub use user_input_line_repository::UserInputLineRepository;
pub use survey_user_input_predefined_question_repository::SurveyUserInputPredefinedQuestionRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
pub use attempt_repository::AttemptRepository;
pub use scoring_repository::{FrozenQuestion, ScoringRepository};
pub use survey_session_repository::SurveySessionRepository;
// END CUSTOM
