//! Repository for Question entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Question, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Question;

/// Table name for Question entities
pub const TABLE_NAME: &str = "survey.survey_questions";

/// Repository for Question entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct QuestionRepository(
    backbone_orm::GenericCrudRepository<Question, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for QuestionRepository {
    type Target = backbone_orm::GenericCrudRepository<Question, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl QuestionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(QuestionRepository, Question, soft_delete);
