//! Repository for Survey entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Survey, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Survey;

/// Table name for Survey entities
pub const TABLE_NAME: &str = "survey.survey_surveys";

/// Repository for Survey entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SurveyRepository(
    backbone_orm::GenericCrudRepository<Survey, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SurveyRepository {
    type Target = backbone_orm::GenericCrudRepository<Survey, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SurveyRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(SurveyRepository, Survey, soft_delete);
