//! Repository for SurveyQuestionTriggeringAnswer entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SurveyQuestionTriggeringAnswer, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::SurveyQuestionTriggeringAnswer;

/// Table name for SurveyQuestionTriggeringAnswer entities
pub const TABLE_NAME: &str = "survey.survey_question_triggering_answers";

/// Repository for SurveyQuestionTriggeringAnswer entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SurveyQuestionTriggeringAnswerRepository(
    backbone_orm::GenericCrudRepository<SurveyQuestionTriggeringAnswer, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SurveyQuestionTriggeringAnswerRepository {
    type Target = backbone_orm::GenericCrudRepository<SurveyQuestionTriggeringAnswer, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SurveyQuestionTriggeringAnswerRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(SurveyQuestionTriggeringAnswerRepository, SurveyQuestionTriggeringAnswer, soft_delete);
