//! Repository for SurveyUserInputPredefinedQuestion entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SurveyUserInputPredefinedQuestion, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::SurveyUserInputPredefinedQuestion;

/// Table name for SurveyUserInputPredefinedQuestion entities
pub const TABLE_NAME: &str = "survey.survey_user_input_predefined_questions";

/// Repository for SurveyUserInputPredefinedQuestion entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SurveyUserInputPredefinedQuestionRepository(
    backbone_orm::GenericCrudRepository<SurveyUserInputPredefinedQuestion, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SurveyUserInputPredefinedQuestionRepository {
    type Target = backbone_orm::GenericCrudRepository<SurveyUserInputPredefinedQuestion, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SurveyUserInputPredefinedQuestionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(SurveyUserInputPredefinedQuestionRepository, SurveyUserInputPredefinedQuestion, soft_delete);
