//! Repository for SurveySurveyLang entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SurveySurveyLang, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::SurveySurveyLang;

/// Table name for SurveySurveyLang entities
pub const TABLE_NAME: &str = "survey.survey_survey_langs";

/// Repository for SurveySurveyLang entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SurveySurveyLangRepository(
    backbone_orm::GenericCrudRepository<SurveySurveyLang, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SurveySurveyLangRepository {
    type Target = backbone_orm::GenericCrudRepository<SurveySurveyLang, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SurveySurveyLangRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(SurveySurveyLangRepository, SurveySurveyLang, soft_delete);
