//! Repository for UserInput entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<UserInput, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::UserInput;

/// Table name for UserInput entities
pub const TABLE_NAME: &str = "survey.survey_user_inputs";

/// Repository for UserInput entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct UserInputRepository(
    backbone_orm::GenericCrudRepository<UserInput, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for UserInputRepository {
    type Target = backbone_orm::GenericCrudRepository<UserInput, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl UserInputRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(UserInputRepository, UserInput, soft_delete);
