//! Validator for Question entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Question>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Question;

/// Validator type alias for Question entities.
pub type QuestionValidator = EntityValidator<Question>;

/// Build a validator for Question with all schema-defined field rules.
pub fn question_validator() -> QuestionValidator {
    EntityValidator::new()
        .rule(RequiredString::new("title", |e: &Question| &e.title))
        .rule(OptionalNotBlank::new("description", |e: &Question| e.description.as_deref()))
        .rule(OptionalNotBlank::new("question_placeholder", |e: &Question| e.question_placeholder.as_deref()))
        .rule(OptionalNotBlank::new("background_image", |e: &Question| e.background_image.as_deref()))
        .rule(OptionalNotBlank::new("scale_min_label", |e: &Question| e.scale_min_label.as_deref()))
        .rule(OptionalNotBlank::new("scale_mid_label", |e: &Question| e.scale_mid_label.as_deref()))
        .rule(OptionalNotBlank::new("scale_max_label", |e: &Question| e.scale_max_label.as_deref()))
        .rule(OptionalNotBlank::new("comments_message", |e: &Question| e.comments_message.as_deref()))
        .rule(OptionalNotBlank::new("validation_error_msg", |e: &Question| e.validation_error_msg.as_deref()))
        .rule(OptionalNotBlank::new("constr_error_msg", |e: &Question| e.constr_error_msg.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
