//! Validator for Survey entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Survey>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Survey;

/// Validator type alias for Survey entities.
pub type SurveyValidator = EntityValidator<Survey>;

/// Build a validator for Survey with all schema-defined field rules.
pub fn survey_validator() -> SurveyValidator {
    EntityValidator::new()
        .rule(RequiredString::new("title", |e: &Survey| &e.title))
        .rule(OptionalNotBlank::new("description", |e: &Survey| e.description.as_deref()))
        .rule(OptionalNotBlank::new("description_done", |e: &Survey| e.description_done.as_deref()))
        .rule(OptionalNotBlank::new("background_image", |e: &Survey| e.background_image.as_deref()))
        .rule(RequiredString::new("access_token", |e: &Survey| &e.access_token))
        .rule(OptionalNotBlank::new("certification_badge_key", |e: &Survey| e.certification_badge_key.as_deref()))
        .rule(OptionalNotBlank::new("session_code", |e: &Survey| e.session_code.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
