//! Validator for SurveySurveyLang entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<SurveySurveyLang>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::SurveySurveyLang;

/// Validator type alias for SurveySurveyLang entities.
pub type SurveySurveyLangValidator = EntityValidator<SurveySurveyLang>;

/// Build a validator for SurveySurveyLang with all schema-defined field rules.
pub fn survey_survey_lang_validator() -> SurveySurveyLangValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
