//! Validator for SurveyUserInputPredefinedQuestion entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<SurveyUserInputPredefinedQuestion>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::SurveyUserInputPredefinedQuestion;

/// Validator type alias for SurveyUserInputPredefinedQuestion entities.
pub type SurveyUserInputPredefinedQuestionValidator = EntityValidator<SurveyUserInputPredefinedQuestion>;

/// Build a validator for SurveyUserInputPredefinedQuestion with all schema-defined field rules.
pub fn survey_user_input_predefined_question_validator() -> SurveyUserInputPredefinedQuestionValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
