//! Validator for SurveyQuestionTriggeringAnswer entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<SurveyQuestionTriggeringAnswer>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::SurveyQuestionTriggeringAnswer;

/// Validator type alias for SurveyQuestionTriggeringAnswer entities.
pub type SurveyQuestionTriggeringAnswerValidator = EntityValidator<SurveyQuestionTriggeringAnswer>;

/// Build a validator for SurveyQuestionTriggeringAnswer with all schema-defined field rules.
pub fn survey_question_triggering_answer_validator() -> SurveyQuestionTriggeringAnswerValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
