//! Validator for UserInputLine entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<UserInputLine>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::UserInputLine;

/// Validator type alias for UserInputLine entities.
pub type UserInputLineValidator = EntityValidator<UserInputLine>;

/// Build a validator for UserInputLine with all schema-defined field rules.
pub fn user_input_line_validator() -> UserInputLineValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("value_char_box", |e: &UserInputLine| e.value_char_box.as_deref()))
        .rule(OptionalNotBlank::new("value_text_box", |e: &UserInputLine| e.value_text_box.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
