//! Validator for UserInput entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<UserInput>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::UserInput;

/// Validator type alias for UserInput entities.
pub type UserInputValidator = EntityValidator<UserInput>;

/// Build a validator for UserInput with all schema-defined field rules.
pub fn user_input_validator() -> UserInputValidator {
    EntityValidator::new()
        .rule(RequiredString::new("token_nonce", |e: &UserInput| &e.token_nonce))
        .rule(OptionalNotBlank::new("invite_token", |e: &UserInput| e.invite_token.as_deref()))
        .rule(OptionalNotBlank::new("email", |e: &UserInput| e.email.as_deref()))
        .rule(OptionalNotBlank::new("nickname", |e: &UserInput| e.nickname.as_deref()))
        .rule(OptionalNotBlank::new("wire_identity_key", |e: &UserInput| e.wire_identity_key.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
