//! Domain Entities
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod question;
pub mod question_answer;
pub mod survey_question_triggering_answer;
pub mod survey;
pub mod survey_survey_restrict_user;
pub mod survey_survey_lang;
pub mod user_input;
pub mod user_input_line;
pub mod survey_user_input_predefined_question;
pub mod survey_question_type;
pub mod survey_matrix_subtype;
pub mod survey_survey_type;
pub mod survey_access_mode;
pub mod survey_scoring_type;
pub mod survey_session_state;
pub mod survey_questions_layout;
pub mod survey_questions_selection;
pub mod survey_report_layout;
pub mod survey_progression_mode;
pub mod survey_invite_existing_mode;
pub mod survey_input_state;
pub mod survey_answer_type;

// Re-exports
pub use question::Question;
pub use question::QuestionBuilder;
pub use question::QuestionId;
pub use question_answer::QuestionAnswer;
pub use question_answer::QuestionAnswerBuilder;
pub use question_answer::QuestionAnswerId;
pub use survey_question_triggering_answer::SurveyQuestionTriggeringAnswer;
pub use survey_question_triggering_answer::SurveyQuestionTriggeringAnswerBuilder;
pub use survey_question_triggering_answer::SurveyQuestionTriggeringAnswerId;
pub use survey::Survey;
pub use survey::SurveyBuilder;
pub use survey::SurveyId;
pub use survey_survey_restrict_user::SurveySurveyRestrictUser;
pub use survey_survey_restrict_user::SurveySurveyRestrictUserBuilder;
pub use survey_survey_restrict_user::SurveySurveyRestrictUserId;
pub use survey_survey_lang::SurveySurveyLang;
pub use survey_survey_lang::SurveySurveyLangBuilder;
pub use survey_survey_lang::SurveySurveyLangId;
pub use user_input::UserInput;
pub use user_input::UserInputBuilder;
pub use user_input::UserInputId;
pub use user_input_line::UserInputLine;
pub use user_input_line::UserInputLineBuilder;
pub use user_input_line::UserInputLineId;
pub use survey_user_input_predefined_question::SurveyUserInputPredefinedQuestion;
pub use survey_user_input_predefined_question::SurveyUserInputPredefinedQuestionBuilder;
pub use survey_user_input_predefined_question::SurveyUserInputPredefinedQuestionId;
pub use survey_question_type::SurveyQuestionType;
pub use survey_matrix_subtype::SurveyMatrixSubtype;
pub use survey_survey_type::SurveySurveyType;
pub use survey_access_mode::SurveyAccessMode;
pub use survey_scoring_type::SurveyScoringType;
pub use survey_session_state::SurveySessionState;
pub use survey_questions_layout::SurveyQuestionsLayout;
pub use survey_questions_selection::SurveyQuestionsSelection;
pub use survey_report_layout::SurveyReportLayout;
pub use survey_progression_mode::SurveyProgressionMode;
pub use survey_invite_existing_mode::SurveyInviteExistingMode;
pub use survey_input_state::SurveyInputState;
pub use survey_answer_type::SurveyAnswerType;

// ==========================================================================
// Entity Trait
// ==========================================================================

use std::fmt::Debug;

/// Trait for domain entities
///
/// All generated entities implement this trait, providing
/// a common interface for working with domain objects.
pub trait Entity: Debug + Clone {
    /// The type of the entity's unique identifier
    type Id: Debug + Clone + PartialEq;

    /// Get the entity's unique identifier
    fn entity_id(&self) -> &Self::Id;

    /// Get the entity type name
    fn entity_type() -> &'static str;
}

// ==========================================================================
// Audit Metadata
// ==========================================================================

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

/// Audit metadata stored as JSONB in the database
///
/// This struct consolidates audit fields (timestamps and actors) into a single
/// JSONB column for efficient storage and flexible querying.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct AuditMetadata {
    /// Timestamp when the record was created
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was last updated
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was soft-deleted
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<DateTime<Utc>>,

    /// User ID who created the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Uuid>,

    /// User ID who last updated the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<Uuid>,

    /// User ID who deleted the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_by: Option<Uuid>,
}

impl AuditMetadata {
    /// Create new audit metadata with created_at set to now
    pub fn new() -> Self {
        Self {
            created_at: Some(Utc::now()),
            ..Default::default()
        }
    }

    /// Create with creator ID
    pub fn with_creator(creator_id: Uuid) -> Self {
        Self {
            created_at: Some(Utc::now()),
            created_by: Some(creator_id),
            ..Default::default()
        }
    }

    /// Touch the record (update updated_at)
    pub fn touch(&mut self) {
        self.updated_at = Some(Utc::now());
    }

    /// Touch with updater ID
    pub fn touch_by(&mut self, updater_id: Uuid) {
        self.updated_at = Some(Utc::now());
        self.updated_by = Some(updater_id);
    }

    /// Soft delete the record
    pub fn soft_delete(&mut self) {
        self.deleted_at = Some(Utc::now());
    }

    /// Soft delete with deleter ID
    pub fn soft_delete_by(&mut self, deleter_id: Uuid) {
        self.deleted_at = Some(Utc::now());
        self.deleted_by = Some(deleter_id);
    }

    /// Restore a soft-deleted record
    pub fn restore(&mut self) {
        self.deleted_at = None;
        self.deleted_by = None;
    }

    /// Check if record is deleted
    pub fn is_deleted(&self) -> bool {
        self.deleted_at.is_some()
    }

    /// Check if record is active (not deleted)
    pub fn is_active(&self) -> bool {
        self.deleted_at.is_none()
    }
}
