//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod question_api_test;
pub mod question_answer_api_test;
pub mod survey_question_triggering_answer_api_test;
pub mod survey_api_test;
pub mod survey_survey_restrict_user_api_test;
pub mod survey_survey_lang_api_test;
pub mod user_input_api_test;
pub mod user_input_line_api_test;
pub mod survey_user_input_predefined_question_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use question_api_test::*;
pub use question_answer_api_test::*;
pub use survey_question_triggering_answer_api_test::*;
pub use survey_api_test::*;
pub use survey_survey_restrict_user_api_test::*;
pub use survey_survey_lang_api_test::*;
pub use user_input_api_test::*;
pub use user_input_line_api_test::*;
pub use survey_user_input_predefined_question_api_test::*;
