//! Question API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Question CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// QUESTION TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Question
pub struct QuestionTestData;

impl TestDataGenerator for QuestionTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "survey_id": Uuid::new_v4().to_string(),
            "sequence": 1,
            "is_page": false,
            "question_type": null,
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "question_placeholder": null,
            "background_image": null,
            "random_questions_count": 1,
            "is_scored_question": false,
            "answer_numerical_box": null,
            "answer_date": null,
            "answer_datetime": null,
            "answer_score": 1.0,
            "save_as_email": false,
            "save_as_nickname": false,
            "matrix_subtype": "simple",
            "scale_min": 1,
            "scale_max": 1,
            "scale_min_label": null,
            "scale_mid_label": null,
            "scale_max_label": null,
            "is_time_limited": false,
            "time_limit": null,
            "is_time_customized": false,
            "comments_allowed": false,
            "comments_message": null,
            "comment_count_as_answer": false,
            "validation_required": false,
            "validation_email": false,
            "validation_length_min": 1,
            "validation_length_max": 1,
            "validation_min_float_value": null,
            "validation_max_float_value": null,
            "validation_min_date": null,
            "validation_max_date": null,
            "validation_min_datetime": null,
            "validation_max_datetime": null,
            "validation_error_msg": null,
            "constr_error_msg": null,
            "constr_mandatory": false,
            "page_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "survey_id": Uuid::new_v4().to_string(),
            "sequence": 1,
            "is_page": false,
            "question_type": null,
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "question_placeholder": null,
            "background_image": null,
            "random_questions_count": 1,
            "is_scored_question": false,
            "answer_numerical_box": null,
            "answer_date": null,
            "answer_datetime": null,
            "answer_score": 1.0,
            "save_as_email": false,
            "save_as_nickname": false,
            "matrix_subtype": "simple",
            "scale_min": 1,
            "scale_max": 1,
            "scale_min_label": null,
            "scale_mid_label": null,
            "scale_max_label": null,
            "is_time_limited": false,
            "time_limit": null,
            "is_time_customized": false,
            "comments_allowed": false,
            "comments_message": null,
            "comment_count_as_answer": false,
            "validation_required": false,
            "validation_email": false,
            "validation_length_min": 1,
            "validation_length_max": 1,
            "validation_min_float_value": null,
            "validation_max_float_value": null,
            "validation_min_date": null,
            "validation_max_date": null,
            "validation_min_datetime": null,
            "validation_max_datetime": null,
            "validation_error_msg": null,
            "constr_error_msg": null,
            "constr_mandatory": false,
            "page_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/survey_surveys", &super::survey_api_test::SurveyTestData).await {
            deps.push(("survey_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// QUESTION API TEST
// ============================================================================

/// Question API test suite
pub struct QuestionApiTest {
    inner: GenericCrudTest<QuestionTestData>,
}

impl QuestionApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/survey_questions", "Question");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, QuestionTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for QuestionApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_question_crud() {
        let mut test = QuestionApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Question specific tests here
// <<< CUSTOM TESTS END >>>
