//! Survey API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Survey CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// SURVEY TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Survey
pub struct SurveyTestData;

impl TestDataGenerator for SurveyTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "survey_type": "survey",
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "description_done": null,
            "background_image": null,
            "active": false,
            "user_id": null,
            "access_token": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "questions_layout": "page_per_question",
            "questions_selection": "all",
            "progression_mode": "percent",
            "access_mode": "public",
            "users_login_required": false,
            "users_can_go_back": false,
            "is_attempts_limited": false,
            "attempts_limit": 1,
            "is_time_limited": false,
            "time_limit": 1.0,
            "scoring_type": "no_scoring",
            "scoring_success_min": 1.0,
            "certification": false,
            "certification_mail_template_id": null,
            "certification_report_layout": "modern_purple",
            "certification_give_badge": false,
            "certification_badge_key": null,
            "session_state": null,
            "session_code": null,
            "session_question_id": null,
            "session_start_time": null,
            "session_question_start_time": null,
            "session_speed_rating": false,
            "session_speed_rating_time_limit": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "survey_type": "survey",
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "description_done": null,
            "background_image": null,
            "active": false,
            "user_id": null,
            "access_token": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "questions_layout": "page_per_question",
            "questions_selection": "all",
            "progression_mode": "percent",
            "access_mode": "public",
            "users_login_required": false,
            "users_can_go_back": false,
            "is_attempts_limited": false,
            "attempts_limit": 1,
            "is_time_limited": false,
            "time_limit": 1.0,
            "scoring_type": "no_scoring",
            "scoring_success_min": 1.0,
            "certification": false,
            "certification_mail_template_id": null,
            "certification_report_layout": "modern_purple",
            "certification_give_badge": false,
            "certification_badge_key": null,
            "session_state": null,
            "session_code": null,
            "session_question_id": null,
            "session_start_time": null,
            "session_question_start_time": null,
            "session_speed_rating": false,
            "session_speed_rating_time_limit": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// SURVEY API TEST
// ============================================================================

/// Survey API test suite
pub struct SurveyApiTest {
    inner: GenericCrudTest<SurveyTestData>,
}

impl SurveyApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/survey_surveys", "Survey");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, SurveyTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for SurveyApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_survey_crud() {
        let mut test = SurveyApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Survey specific tests here
// <<< CUSTOM TESTS END >>>
