//! UserInput API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the UserInput CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// USERINPUT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for UserInput
pub struct UserInputTestData;

impl TestDataGenerator for UserInputTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "survey_id": Uuid::new_v4().to_string(),
            "token_nonce": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "token_expires_at": now,
            "invite_token": null,
            "partner_id": null,
            "email": null,
            "nickname": null,
            "user_id": null,
            "wire_identity_key": null,
            "test_entry": false,
            "state": "new",
            "start_datetime": null,
            "end_datetime": null,
            "deadline": null,
            "is_session_answer": false,
            "last_displayed_page_id": null,
            "scoring_percentage": 1.0,
            "scoring_total": 1.0,
            "scoring_success": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "survey_id": Uuid::new_v4().to_string(),
            "token_nonce": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "token_expires_at": now,
            "invite_token": null,
            "partner_id": null,
            "email": null,
            "nickname": null,
            "user_id": null,
            "wire_identity_key": null,
            "test_entry": false,
            "state": "new",
            "start_datetime": null,
            "end_datetime": null,
            "deadline": null,
            "is_session_answer": false,
            "last_displayed_page_id": null,
            "scoring_percentage": 1.0,
            "scoring_total": 1.0,
            "scoring_success": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/survey_surveys", &super::survey_api_test::SurveyTestData).await {
            deps.push(("survey_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// USERINPUT API TEST
// ============================================================================

/// UserInput API test suite
pub struct UserInputApiTest {
    inner: GenericCrudTest<UserInputTestData>,
}

impl UserInputApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/survey_user_inputs", "UserInput");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, UserInputTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for UserInputApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_user_input_crud() {
        let mut test = UserInputApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add UserInput specific tests here
// <<< CUSTOM TESTS END >>>
