//! Survey Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::QuestionService;
use crate::application::service::QuestionAnswerService;
use crate::application::service::SurveyQuestionTriggeringAnswerService;
use crate::application::service::SurveyService;
use crate::application::service::SurveySurveyRestrictUserService;
use crate::application::service::SurveySurveyLangService;
use crate::application::service::UserInputService;
use crate::application::service::UserInputLineService;
use crate::application::service::SurveyUserInputPredefinedQuestionService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Question service
    pub question_service: Arc<QuestionService>,
    /// QuestionAnswer service
    pub question_answer_service: Arc<QuestionAnswerService>,
    /// SurveyQuestionTriggeringAnswer service
    pub survey_question_triggering_answer_service: Arc<SurveyQuestionTriggeringAnswerService>,
    /// Survey service
    pub survey_service: Arc<SurveyService>,
    /// SurveySurveyRestrictUser service
    pub survey_survey_restrict_user_service: Arc<SurveySurveyRestrictUserService>,
    /// SurveySurveyLang service
    pub survey_survey_lang_service: Arc<SurveySurveyLangService>,
    /// UserInput service
    pub user_input_service: Arc<UserInputService>,
    /// UserInputLine service
    pub user_input_line_service: Arc<UserInputLineService>,
    /// SurveyUserInputPredefinedQuestion service
    pub survey_user_input_predefined_question_service: Arc<SurveyUserInputPredefinedQuestionService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        question_service: Arc<QuestionService>,
        question_answer_service: Arc<QuestionAnswerService>,
        survey_question_triggering_answer_service: Arc<SurveyQuestionTriggeringAnswerService>,
        survey_service: Arc<SurveyService>,
        survey_survey_restrict_user_service: Arc<SurveySurveyRestrictUserService>,
        survey_survey_lang_service: Arc<SurveySurveyLangService>,
        user_input_service: Arc<UserInputService>,
        user_input_line_service: Arc<UserInputLineService>,
        survey_user_input_predefined_question_service: Arc<SurveyUserInputPredefinedQuestionService>
    ) -> Self {
        Self {
            question_service,
            question_answer_service,
            survey_question_triggering_answer_service,
            survey_service,
            survey_survey_restrict_user_service,
            survey_survey_lang_service,
            user_input_service,
            user_input_line_service,
            survey_user_input_predefined_question_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::SurveyModule) -> Self {
        Self {
            question_service: module.question_service.clone(),
            question_answer_service: module.question_answer_service.clone(),
            survey_question_triggering_answer_service: module.survey_question_triggering_answer_service.clone(),
            survey_service: module.survey_service.clone(),
            survey_survey_restrict_user_service: module.survey_survey_restrict_user_service.clone(),
            survey_survey_lang_service: module.survey_survey_lang_service.clone(),
            user_input_service: module.user_input_service.clone(),
            user_input_line_service: module.user_input_line_service.clone(),
            survey_user_input_predefined_question_service: module.survey_user_input_predefined_question_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    question_service: Option<Arc<QuestionService>>,
    question_answer_service: Option<Arc<QuestionAnswerService>>,
    survey_question_triggering_answer_service: Option<Arc<SurveyQuestionTriggeringAnswerService>>,
    survey_service: Option<Arc<SurveyService>>,
    survey_survey_restrict_user_service: Option<Arc<SurveySurveyRestrictUserService>>,
    survey_survey_lang_service: Option<Arc<SurveySurveyLangService>>,
    user_input_service: Option<Arc<UserInputService>>,
    user_input_line_service: Option<Arc<UserInputLineService>>,
    survey_user_input_predefined_question_service: Option<Arc<SurveyUserInputPredefinedQuestionService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Question service.
    pub fn with_question_service(mut self, service: Arc<QuestionService>) -> Self {
        self.question_service = Some(service);
        self
    }

    /// Set the QuestionAnswer service.
    pub fn with_question_answer_service(mut self, service: Arc<QuestionAnswerService>) -> Self {
        self.question_answer_service = Some(service);
        self
    }

    /// Set the SurveyQuestionTriggeringAnswer service.
    pub fn with_survey_question_triggering_answer_service(mut self, service: Arc<SurveyQuestionTriggeringAnswerService>) -> Self {
        self.survey_question_triggering_answer_service = Some(service);
        self
    }

    /// Set the Survey service.
    pub fn with_survey_service(mut self, service: Arc<SurveyService>) -> Self {
        self.survey_service = Some(service);
        self
    }

    /// Set the SurveySurveyRestrictUser service.
    pub fn with_survey_survey_restrict_user_service(mut self, service: Arc<SurveySurveyRestrictUserService>) -> Self {
        self.survey_survey_restrict_user_service = Some(service);
        self
    }

    /// Set the SurveySurveyLang service.
    pub fn with_survey_survey_lang_service(mut self, service: Arc<SurveySurveyLangService>) -> Self {
        self.survey_survey_lang_service = Some(service);
        self
    }

    /// Set the UserInput service.
    pub fn with_user_input_service(mut self, service: Arc<UserInputService>) -> Self {
        self.user_input_service = Some(service);
        self
    }

    /// Set the UserInputLine service.
    pub fn with_user_input_line_service(mut self, service: Arc<UserInputLineService>) -> Self {
        self.user_input_line_service = Some(service);
        self
    }

    /// Set the SurveyUserInputPredefinedQuestion service.
    pub fn with_survey_user_input_predefined_question_service(mut self, service: Arc<SurveyUserInputPredefinedQuestionService>) -> Self {
        self.survey_user_input_predefined_question_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            question_service: self.question_service.expect("question_service is required"),
            question_answer_service: self.question_answer_service.expect("question_answer_service is required"),
            survey_question_triggering_answer_service: self.survey_question_triggering_answer_service.expect("survey_question_triggering_answer_service is required"),
            survey_service: self.survey_service.expect("survey_service is required"),
            survey_survey_restrict_user_service: self.survey_survey_restrict_user_service.expect("survey_survey_restrict_user_service is required"),
            survey_survey_lang_service: self.survey_survey_lang_service.expect("survey_survey_lang_service is required"),
            user_input_service: self.user_input_service.expect("user_input_service is required"),
            user_input_line_service: self.user_input_line_service.expect("user_input_line_service is required"),
            survey_user_input_predefined_question_service: self.survey_user_input_predefined_question_service.expect("survey_user_input_predefined_question_service is required"),
        }
    }
}
