//! Public events for Survey module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// QUESTION EVENTS
// ============================================================================

/// Event published when a Question is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionCreatedEvent {
    pub id: QuestionId,
    pub data: QuestionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Question is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionUpdatedEvent {
    pub id: QuestionId,
    pub data: QuestionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Question is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionDeletedEvent {
    pub id: QuestionId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// QUESTIONANSWER EVENTS
// ============================================================================

/// Event published when a QuestionAnswer is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionAnswerCreatedEvent {
    pub id: QuestionAnswerId,
    pub data: QuestionAnswerDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a QuestionAnswer is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionAnswerUpdatedEvent {
    pub id: QuestionAnswerId,
    pub data: QuestionAnswerDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a QuestionAnswer is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionAnswerDeletedEvent {
    pub id: QuestionAnswerId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SURVEYQUESTIONTRIGGERINGANSWER EVENTS
// ============================================================================

/// Event published when a SurveyQuestionTriggeringAnswer is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveyQuestionTriggeringAnswerCreatedEvent {
    pub id: SurveyQuestionTriggeringAnswerId,
    pub data: SurveyQuestionTriggeringAnswerDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SurveyQuestionTriggeringAnswer is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveyQuestionTriggeringAnswerUpdatedEvent {
    pub id: SurveyQuestionTriggeringAnswerId,
    pub data: SurveyQuestionTriggeringAnswerDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SurveyQuestionTriggeringAnswer is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveyQuestionTriggeringAnswerDeletedEvent {
    pub id: SurveyQuestionTriggeringAnswerId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SURVEY EVENTS
// ============================================================================

/// Event published when a Survey is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveyCreatedEvent {
    pub id: SurveyId,
    pub data: SurveyDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Survey is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveyUpdatedEvent {
    pub id: SurveyId,
    pub data: SurveyDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Survey is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveyDeletedEvent {
    pub id: SurveyId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SURVEYSURVEYRESTRICTUSER EVENTS
// ============================================================================

/// Event published when a SurveySurveyRestrictUser is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveySurveyRestrictUserCreatedEvent {
    pub id: SurveySurveyRestrictUserId,
    pub data: SurveySurveyRestrictUserDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SurveySurveyRestrictUser is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveySurveyRestrictUserUpdatedEvent {
    pub id: SurveySurveyRestrictUserId,
    pub data: SurveySurveyRestrictUserDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SurveySurveyRestrictUser is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveySurveyRestrictUserDeletedEvent {
    pub id: SurveySurveyRestrictUserId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SURVEYSURVEYLANG EVENTS
// ============================================================================

/// Event published when a SurveySurveyLang is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveySurveyLangCreatedEvent {
    pub id: SurveySurveyLangId,
    pub data: SurveySurveyLangDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SurveySurveyLang is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveySurveyLangUpdatedEvent {
    pub id: SurveySurveyLangId,
    pub data: SurveySurveyLangDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SurveySurveyLang is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveySurveyLangDeletedEvent {
    pub id: SurveySurveyLangId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// USERINPUT EVENTS
// ============================================================================

/// Event published when a UserInput is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserInputCreatedEvent {
    pub id: UserInputId,
    pub data: UserInputDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a UserInput is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserInputUpdatedEvent {
    pub id: UserInputId,
    pub data: UserInputDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a UserInput is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserInputDeletedEvent {
    pub id: UserInputId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// USERINPUTLINE EVENTS
// ============================================================================

/// Event published when a UserInputLine is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserInputLineCreatedEvent {
    pub id: UserInputLineId,
    pub data: UserInputLineDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a UserInputLine is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserInputLineUpdatedEvent {
    pub id: UserInputLineId,
    pub data: UserInputLineDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a UserInputLine is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserInputLineDeletedEvent {
    pub id: UserInputLineId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SURVEYUSERINPUTPREDEFINEDQUESTION EVENTS
// ============================================================================

/// Event published when a SurveyUserInputPredefinedQuestion is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveyUserInputPredefinedQuestionCreatedEvent {
    pub id: SurveyUserInputPredefinedQuestionId,
    pub data: SurveyUserInputPredefinedQuestionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SurveyUserInputPredefinedQuestion is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveyUserInputPredefinedQuestionUpdatedEvent {
    pub id: SurveyUserInputPredefinedQuestionId,
    pub data: SurveyUserInputPredefinedQuestionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SurveyUserInputPredefinedQuestion is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveyUserInputPredefinedQuestionDeletedEvent {
    pub id: SurveyUserInputPredefinedQuestionId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Survey module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum SurveyEvent {
    QuestionCreated(QuestionCreatedEvent),
    QuestionUpdated(QuestionUpdatedEvent),
    QuestionDeleted(QuestionDeletedEvent),
    QuestionAnswerCreated(QuestionAnswerCreatedEvent),
    QuestionAnswerUpdated(QuestionAnswerUpdatedEvent),
    QuestionAnswerDeleted(QuestionAnswerDeletedEvent),
    SurveyQuestionTriggeringAnswerCreated(SurveyQuestionTriggeringAnswerCreatedEvent),
    SurveyQuestionTriggeringAnswerUpdated(SurveyQuestionTriggeringAnswerUpdatedEvent),
    SurveyQuestionTriggeringAnswerDeleted(SurveyQuestionTriggeringAnswerDeletedEvent),
    SurveyCreated(SurveyCreatedEvent),
    SurveyUpdated(SurveyUpdatedEvent),
    SurveyDeleted(SurveyDeletedEvent),
    SurveySurveyRestrictUserCreated(SurveySurveyRestrictUserCreatedEvent),
    SurveySurveyRestrictUserUpdated(SurveySurveyRestrictUserUpdatedEvent),
    SurveySurveyRestrictUserDeleted(SurveySurveyRestrictUserDeletedEvent),
    SurveySurveyLangCreated(SurveySurveyLangCreatedEvent),
    SurveySurveyLangUpdated(SurveySurveyLangUpdatedEvent),
    SurveySurveyLangDeleted(SurveySurveyLangDeletedEvent),
    UserInputCreated(UserInputCreatedEvent),
    UserInputUpdated(UserInputUpdatedEvent),
    UserInputDeleted(UserInputDeletedEvent),
    UserInputLineCreated(UserInputLineCreatedEvent),
    UserInputLineUpdated(UserInputLineUpdatedEvent),
    UserInputLineDeleted(UserInputLineDeletedEvent),
    SurveyUserInputPredefinedQuestionCreated(SurveyUserInputPredefinedQuestionCreatedEvent),
    SurveyUserInputPredefinedQuestionUpdated(SurveyUserInputPredefinedQuestionUpdatedEvent),
    SurveyUserInputPredefinedQuestionDeleted(SurveyUserInputPredefinedQuestionDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveyEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for SurveyEventMetadata {
    fn default() -> Self {
        Self {
            module: "survey",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
