//! Public types for Survey module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use crate::domain::entity::*;

// ============================================================================
// QUESTION TYPES
// ============================================================================

/// Type-safe ID for Question
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct QuestionId(pub Uuid);

impl QuestionId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for QuestionId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<QuestionId> for Uuid {
    fn from(id: QuestionId) -> Self {
        id.0
    }
}

/// Data transfer object for Question
///
/// This is the public representation of Question for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionDto {
    pub id: QuestionId,
    pub survey_id: Uuid,
    pub sequence: i32,
    pub is_page: bool,
    pub question_type: Option<SurveyQuestionType>,
    pub title: String,
    pub description: Option<String>,
    pub question_placeholder: Option<String>,
    pub background_image: Option<String>,
    pub random_questions_count: i32,
    pub is_scored_question: bool,
    pub answer_numerical_box: Option<f64>,
    pub answer_date: Option<NaiveDate>,
    pub answer_datetime: Option<DateTime<Utc>>,
    pub answer_score: f64,
    pub save_as_email: bool,
    pub save_as_nickname: bool,
    pub matrix_subtype: SurveyMatrixSubtype,
    pub scale_min: i32,
    pub scale_max: i32,
    pub scale_min_label: Option<String>,
    pub scale_mid_label: Option<String>,
    pub scale_max_label: Option<String>,
    pub is_time_limited: bool,
    pub time_limit: Option<i32>,
    pub is_time_customized: bool,
    pub comments_allowed: bool,
    pub comments_message: Option<String>,
    pub comment_count_as_answer: bool,
    pub validation_required: bool,
    pub validation_email: bool,
    pub validation_length_min: i32,
    pub validation_length_max: i32,
    pub validation_min_float_value: Option<f64>,
    pub validation_max_float_value: Option<f64>,
    pub validation_min_date: Option<NaiveDate>,
    pub validation_max_date: Option<NaiveDate>,
    pub validation_min_datetime: Option<DateTime<Utc>>,
    pub validation_max_datetime: Option<DateTime<Utc>>,
    pub validation_error_msg: Option<String>,
    pub constr_error_msg: Option<String>,
    pub constr_mandatory: bool,
    pub page_id: Option<Uuid>,
    pub metadata: serde_json::Value,
}

/// Summary view of Question for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionSummary {
    pub id: QuestionId,
    pub title: String,
}

/// Reference to Question for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionRef {
    pub id: QuestionId,
}

// ============================================================================
// QUESTIONANSWER TYPES
// ============================================================================

/// Type-safe ID for QuestionAnswer
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct QuestionAnswerId(pub Uuid);

impl QuestionAnswerId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for QuestionAnswerId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<QuestionAnswerId> for Uuid {
    fn from(id: QuestionAnswerId) -> Self {
        id.0
    }
}

/// Data transfer object for QuestionAnswer
///
/// This is the public representation of QuestionAnswer for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionAnswerDto {
    pub id: QuestionAnswerId,
    pub question_id: Option<Uuid>,
    pub matrix_question_id: Option<Uuid>,
    pub sequence: i32,
    pub value: Option<String>,
    pub value_image: Option<String>,
    pub value_image_filename: Option<String>,
    pub is_correct: bool,
    pub answer_score: f64,
    pub metadata: serde_json::Value,
}

/// Summary view of QuestionAnswer for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionAnswerSummary {
    pub id: QuestionAnswerId,
}

/// Reference to QuestionAnswer for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionAnswerRef {
    pub id: QuestionAnswerId,
}

// ============================================================================
// SURVEYQUESTIONTRIGGERINGANSWER TYPES
// ============================================================================

/// Type-safe ID for SurveyQuestionTriggeringAnswer
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SurveyQuestionTriggeringAnswerId(pub Uuid);

impl SurveyQuestionTriggeringAnswerId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for SurveyQuestionTriggeringAnswerId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<SurveyQuestionTriggeringAnswerId> for Uuid {
    fn from(id: SurveyQuestionTriggeringAnswerId) -> Self {
        id.0
    }
}

/// Data transfer object for SurveyQuestionTriggeringAnswer
///
/// This is the public representation of SurveyQuestionTriggeringAnswer for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveyQuestionTriggeringAnswerDto {
    pub id: SurveyQuestionTriggeringAnswerId,
    pub question_id: Uuid,
    pub suggested_answer_id: Uuid,
    pub metadata: serde_json::Value,
}

/// Summary view of SurveyQuestionTriggeringAnswer for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveyQuestionTriggeringAnswerSummary {
    pub id: SurveyQuestionTriggeringAnswerId,
}

/// Reference to SurveyQuestionTriggeringAnswer for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveyQuestionTriggeringAnswerRef {
    pub id: SurveyQuestionTriggeringAnswerId,
}

// ============================================================================
// SURVEY TYPES
// ============================================================================

/// Type-safe ID for Survey
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SurveyId(pub Uuid);

impl SurveyId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for SurveyId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<SurveyId> for Uuid {
    fn from(id: SurveyId) -> Self {
        id.0
    }
}

/// Data transfer object for Survey
///
/// This is the public representation of Survey for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveyDto {
    pub id: SurveyId,
    pub survey_type: SurveySurveyType,
    pub title: String,
    pub description: Option<String>,
    pub description_done: Option<String>,
    pub background_image: Option<String>,
    pub active: bool,
    pub user_id: Option<Uuid>,
    pub access_token: String,
    pub questions_layout: SurveyQuestionsLayout,
    pub questions_selection: SurveyQuestionsSelection,
    pub progression_mode: SurveyProgressionMode,
    pub access_mode: SurveyAccessMode,
    pub users_login_required: bool,
    pub users_can_go_back: bool,
    pub is_attempts_limited: bool,
    pub attempts_limit: i32,
    pub is_time_limited: bool,
    pub time_limit: f64,
    pub scoring_type: SurveyScoringType,
    pub scoring_success_min: f64,
    pub certification: bool,
    pub certification_mail_template_id: Option<Uuid>,
    pub certification_report_layout: SurveyReportLayout,
    pub certification_give_badge: bool,
    pub certification_badge_key: Option<String>,
    pub session_state: Option<SurveySessionState>,
    pub session_code: Option<String>,
    pub session_question_id: Option<Uuid>,
    pub session_start_time: Option<DateTime<Utc>>,
    pub session_question_start_time: Option<DateTime<Utc>>,
    pub session_speed_rating: bool,
    pub session_speed_rating_time_limit: Option<i32>,
    pub metadata: serde_json::Value,
}

/// Summary view of Survey for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveySummary {
    pub id: SurveyId,
    pub title: String,
}

/// Reference to Survey for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveyRef {
    pub id: SurveyId,
}

// ============================================================================
// SURVEYSURVEYRESTRICTUSER TYPES
// ============================================================================

/// Type-safe ID for SurveySurveyRestrictUser
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SurveySurveyRestrictUserId(pub Uuid);

impl SurveySurveyRestrictUserId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for SurveySurveyRestrictUserId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<SurveySurveyRestrictUserId> for Uuid {
    fn from(id: SurveySurveyRestrictUserId) -> Self {
        id.0
    }
}

/// Data transfer object for SurveySurveyRestrictUser
///
/// This is the public representation of SurveySurveyRestrictUser for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveySurveyRestrictUserDto {
    pub id: SurveySurveyRestrictUserId,
    pub survey_id: Uuid,
    pub user_id: Uuid,
    pub metadata: serde_json::Value,
}

/// Summary view of SurveySurveyRestrictUser for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveySurveyRestrictUserSummary {
    pub id: SurveySurveyRestrictUserId,
}

/// Reference to SurveySurveyRestrictUser for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveySurveyRestrictUserRef {
    pub id: SurveySurveyRestrictUserId,
}

// ============================================================================
// SURVEYSURVEYLANG TYPES
// ============================================================================

/// Type-safe ID for SurveySurveyLang
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SurveySurveyLangId(pub Uuid);

impl SurveySurveyLangId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for SurveySurveyLangId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<SurveySurveyLangId> for Uuid {
    fn from(id: SurveySurveyLangId) -> Self {
        id.0
    }
}

/// Data transfer object for SurveySurveyLang
///
/// This is the public representation of SurveySurveyLang for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveySurveyLangDto {
    pub id: SurveySurveyLangId,
    pub survey_id: Uuid,
    pub lang_id: Uuid,
    pub metadata: serde_json::Value,
}

/// Summary view of SurveySurveyLang for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveySurveyLangSummary {
    pub id: SurveySurveyLangId,
}

/// Reference to SurveySurveyLang for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveySurveyLangRef {
    pub id: SurveySurveyLangId,
}

// ============================================================================
// USERINPUT TYPES
// ============================================================================

/// Type-safe ID for UserInput
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct UserInputId(pub Uuid);

impl UserInputId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for UserInputId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<UserInputId> for Uuid {
    fn from(id: UserInputId) -> Self {
        id.0
    }
}

/// Data transfer object for UserInput
///
/// This is the public representation of UserInput for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserInputDto {
    pub id: UserInputId,
    pub survey_id: Uuid,
    pub token_nonce: String,
    pub token_expires_at: DateTime<Utc>,
    pub invite_token: Option<String>,
    pub partner_id: Option<Uuid>,
    pub email: Option<String>,
    pub nickname: Option<String>,
    pub user_id: Option<Uuid>,
    pub wire_identity_key: Option<String>,
    pub test_entry: bool,
    pub state: SurveyInputState,
    pub start_datetime: Option<DateTime<Utc>>,
    pub end_datetime: Option<DateTime<Utc>>,
    pub deadline: Option<DateTime<Utc>>,
    pub is_session_answer: bool,
    pub last_displayed_page_id: Option<Uuid>,
    pub scoring_percentage: f64,
    pub scoring_total: f64,
    pub scoring_success: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of UserInput for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserInputSummary {
    pub id: UserInputId,
    pub email: Option<String>,
}

/// Reference to UserInput for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserInputRef {
    pub id: UserInputId,
}

// ============================================================================
// USERINPUTLINE TYPES
// ============================================================================

/// Type-safe ID for UserInputLine
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct UserInputLineId(pub Uuid);

impl UserInputLineId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for UserInputLineId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<UserInputLineId> for Uuid {
    fn from(id: UserInputLineId) -> Self {
        id.0
    }
}

/// Data transfer object for UserInputLine
///
/// This is the public representation of UserInputLine for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserInputLineDto {
    pub id: UserInputLineId,
    pub user_input_id: Uuid,
    pub survey_id: Uuid,
    pub question_id: Uuid,
    pub suggested_answer_id: Option<Uuid>,
    pub matrix_row_id: Option<Uuid>,
    pub skipped: bool,
    pub answer_type: Option<SurveyAnswerType>,
    pub value_char_box: Option<String>,
    pub value_text_box: Option<String>,
    pub value_numerical_box: Option<f64>,
    pub value_scale: Option<i32>,
    pub value_date: Option<NaiveDate>,
    pub value_datetime: Option<DateTime<Utc>>,
    pub answer_score: Option<f64>,
    pub answer_is_correct: Option<bool>,
    pub speed_seconds: Option<i32>,
    pub answered_at: DateTime<Utc>,
    pub metadata: serde_json::Value,
}

/// Summary view of UserInputLine for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserInputLineSummary {
    pub id: UserInputLineId,
}

/// Reference to UserInputLine for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserInputLineRef {
    pub id: UserInputLineId,
}

// ============================================================================
// SURVEYUSERINPUTPREDEFINEDQUESTION TYPES
// ============================================================================

/// Type-safe ID for SurveyUserInputPredefinedQuestion
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SurveyUserInputPredefinedQuestionId(pub Uuid);

impl SurveyUserInputPredefinedQuestionId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for SurveyUserInputPredefinedQuestionId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<SurveyUserInputPredefinedQuestionId> for Uuid {
    fn from(id: SurveyUserInputPredefinedQuestionId) -> Self {
        id.0
    }
}

/// Data transfer object for SurveyUserInputPredefinedQuestion
///
/// This is the public representation of SurveyUserInputPredefinedQuestion for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveyUserInputPredefinedQuestionDto {
    pub id: SurveyUserInputPredefinedQuestionId,
    pub user_input_id: Uuid,
    pub question_id: Uuid,
    pub metadata: serde_json::Value,
}

/// Summary view of SurveyUserInputPredefinedQuestion for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveyUserInputPredefinedQuestionSummary {
    pub id: SurveyUserInputPredefinedQuestionId,
}

/// Reference to SurveyUserInputPredefinedQuestion for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SurveyUserInputPredefinedQuestionRef {
    pub id: SurveyUserInputPredefinedQuestionId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
