//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod question_handler;
pub mod question_answer_handler;
pub mod survey_question_triggering_answer_handler;
pub mod survey_handler;
pub mod survey_survey_restrict_user_handler;
pub mod survey_survey_lang_handler;
pub mod user_input_handler;
pub mod user_input_line_handler;
pub mod survey_user_input_predefined_question_handler;

// <<< CUSTOM
pub mod public_routes;
// END CUSTOM

// Re-exports
pub use question_handler::{create_question_routes, create_question_read_routes, create_question_write_routes};
pub use question_answer_handler::{create_question_answer_routes, create_question_answer_read_routes, create_question_answer_write_routes};
pub use survey_question_triggering_answer_handler::{create_survey_question_triggering_answer_routes, create_survey_question_triggering_answer_read_routes, create_survey_question_triggering_answer_write_routes};
pub use survey_handler::{create_survey_routes, create_survey_read_routes, create_survey_write_routes};
pub use survey_survey_restrict_user_handler::{create_survey_survey_restrict_user_routes, create_survey_survey_restrict_user_read_routes, create_survey_survey_restrict_user_write_routes};
pub use survey_survey_lang_handler::{create_survey_survey_lang_routes, create_survey_survey_lang_read_routes, create_survey_survey_lang_write_routes};
pub use user_input_handler::{create_user_input_routes, create_user_input_read_routes, create_user_input_write_routes};
pub use user_input_line_handler::{create_user_input_line_routes, create_user_input_line_read_routes, create_user_input_line_write_routes};
pub use survey_user_input_predefined_question_handler::{create_survey_user_input_predefined_question_routes, create_survey_user_input_predefined_question_read_routes, create_survey_user_input_predefined_question_write_routes};
// <<< CUSTOM
// END CUSTOM
