//! UserInput REST handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses Axum and backbone-core's BackboneCrudHandler for all 12 CRUD endpoints.

use std::collections::HashMap;
use std::sync::Arc;

use axum::Router;
use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

// Backbone framework imports
use backbone_core::http::{ApiResponse, BackboneCrudHandler};

// Auth integration (optional)
#[cfg(feature = "auth")]
use backbone_auth::middleware::AuthContext;
#[cfg(feature = "auth")]
use backbone_auth::AuthMiddleware;

// Domain imports
use crate::domain::entity::*;
use crate::application::service::{UserInputService, ServiceError};

// DTO imports
use crate::presentation::dto::{CreateUserInputDto, UpdateUserInputDto, PatchUserInputDto, UserInputResponseDto};

use crate::domain::state_machine::{survey_input_stateState, survey_input_stateStateMachine, survey_input_stateTransition};

/// Application error type
#[derive(Debug, thiserror::Error)]
pub enum UserInputError {
    #[error("Not found: {0}")]
    NotFound(String),
    #[error("Validation error: {0}")]
    Validation(String),
    #[error("Database error: {0}")]
    Database(String),
    #[error("Internal error: {0}")]
    Internal(String),
}

impl From<ServiceError> for UserInputError {
    fn from(err: ServiceError) -> Self {
        match err {
            ServiceError::NotFound => Self::NotFound(err.to_string()),
            ServiceError::Validation(ref msg) => Self::Validation(msg.clone()),
            ServiceError::AlreadyExists(ref msg) => Self::Validation(msg.clone()),
            ServiceError::Repository(ref e) => Self::Database(e.to_string()),
            ServiceError::Internal(ref msg) => Self::Internal(msg.clone()),
        }
    }
}

impl axum::response::IntoResponse for UserInputError {
    fn into_response(self) -> axum::response::Response {
        use axum::http::StatusCode;
        use axum::Json;

        let (status, code) = match &self {
            Self::NotFound(_) => (StatusCode::NOT_FOUND, "USERINPUT_NOT_FOUND"),
            Self::Validation(_) => (StatusCode::BAD_REQUEST, "USERINPUT_VALIDATION_ERROR"),
            Self::Database(_) => (StatusCode::INTERNAL_SERVER_ERROR, "USERINPUT_DATABASE_ERROR"),
            Self::Internal(_) => (StatusCode::INTERNAL_SERVER_ERROR, "USERINPUT_INTERNAL_ERROR"),
        };

        let body = serde_json::json!({
            "success": false,
            "error": code,
            "message": self.to_string(),
        });

        (status, Json(body)).into_response()
    }
}

// =============================================================================
// Route Configuration
// =============================================================================

/// Create Axum router with all 16 Backbone endpoints for UserInput.
///
/// # Routes
///
/// | Method | Path | Description |
/// |--------|------|-------------|
/// | GET | /user_inputs | List with pagination |
/// | POST | /user_inputs | Create new |
/// | GET | /user_inputs/:id | Get by ID |
/// | PUT | /user_inputs/:id | Full update |
/// | PATCH | /user_inputs/:id | Partial update |
/// | DELETE | /user_inputs/:id | Soft delete |
/// | POST | /user_inputs/bulk | Bulk create |
/// | POST | /user_inputs/upsert | Upsert |
/// | GET | /user_inputs/trash | List deleted |
/// | POST | /user_inputs/:id/restore | Restore |
/// | DELETE | /user_inputs/empty | Empty trash |
/// | GET | /user_inputs/:id/deleted | Get deleted by ID |
/// | DELETE | /user_inputs/trash/:id | Permanent delete from trash |
/// | GET | /user_inputs/count | Count active entities |
/// | GET | /user_inputs/trash/count | Count deleted entities |
///
/// # Example
///
/// ```text
/// let service = Arc::new(UserInputService::with_repository(repository));
/// let router = create_user_input_routes(service);
/// ```
pub fn create_user_input_routes(service: Arc<UserInputService>) -> Router {
    BackboneCrudHandler::<UserInputService, UserInput, CreateUserInputDto, UpdateUserInputDto, UserInputResponseDto>::routes(
        service,
        "/user_inputs",
    )
}

/// Create Axum router with only the read (GET) endpoints for UserInput.
///
/// Safe for public, unauthenticated exposure (e.g., reference data).
/// Mutations must be served separately via `create_user_input_write_routes`,
/// typically wrapped in an auth middleware layer.
pub fn create_user_input_read_routes(service: Arc<UserInputService>) -> Router {
    BackboneCrudHandler::<UserInputService, UserInput, CreateUserInputDto, UpdateUserInputDto, UserInputResponseDto>::read_routes(
        service,
        "/user_inputs",
    )
}

/// Create Axum router with only the write (mutation) endpoints for UserInput.
///
/// These routes must NOT be publicly exposed. Wrap them with an auth
/// middleware before nesting into the application router.
///
/// # This is unguarded generic CRUD, not a validated write path
///
/// These are plain create/update/patch/delete mutations over the entity row —
/// they bypass all business invariants. If the module exposes a validated write
/// service (e.g. a command router over its domain engine), serve THAT instead
/// for any mutation that must respect domain rules.
pub fn create_user_input_write_routes(service: Arc<UserInputService>) -> Router {
    BackboneCrudHandler::<UserInputService, UserInput, CreateUserInputDto, UpdateUserInputDto, UserInputResponseDto>::write_routes(
        service,
        "/user_inputs",
    )
}

/// Create authenticated routes with auth middleware.
///
/// Requires the `auth` feature flag. The `AuthMiddleware` implementation
/// is responsible for extracting and validating tokens, then providing
/// an `AuthContext` via request extensions.
#[cfg(feature = "auth")]
pub fn create_protected_user_input_routes<A: AuthMiddleware + Send + Sync + 'static>(
    service: Arc<UserInputService>,
    auth: Arc<A>,
) -> Router {
    use axum::middleware;
    use axum::response::IntoResponse;

    let auth_layer = auth.clone();
    create_user_input_routes(service)
        .layer(middleware::from_fn(move |mut req: axum::extract::Request, next: axum::middleware::Next| {
            let auth = auth_layer.clone();
            async move {
                let token = req.headers()
                    .get(axum::http::header::AUTHORIZATION)
                    .and_then(|h| h.to_str().ok())
                    .and_then(|raw| raw.strip_prefix("Bearer ").or_else(|| raw.strip_prefix("bearer ")))
                    .unwrap_or("");
                match auth.authenticate(token).await {
                    Ok(ctx) => {
                        req.extensions_mut().insert(ctx);
                        next.run(req).await
                    }
                    Err(_) => {
                        (axum::http::StatusCode::UNAUTHORIZED,
                         axum::Json(serde_json::json!({
                             "success": false,
                             "error": "unauthorized",
                             "message": "Authentication required"
                         }))
                        ).into_response()
                    }
                }
            }
        }))
}

// =============================================================================
// State Transition Handlers
// =============================================================================

/// Execute begin transition on a UserInput.
///
/// POST /user_inputs/:id/transitions/begin
pub async fn begin_transition(
    axum::extract::State(service): axum::extract::State<Arc<UserInputService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] axum::Extension(auth): axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<UserInputResponseDto>::not_found("UserInput", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<UserInputResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = survey_input_stateTransition::Begin.allowed_roles();
        let has_specific_perm = auth.permissions.iter().any(|p| p == "user_input:transition:begin");
        let has_update_perm = auth.permissions.iter().any(|p| p == "user_input:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<UserInputResponseDto>::error("Insufficient permissions for begin transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: survey_input_stateState = entity.state.to_string().parse()
        .unwrap_or(survey_input_stateState::default());
    let sm = survey_input_stateStateMachine::from_state(current_state);
    if !sm.can_transition(survey_input_stateTransition::Begin) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<UserInputResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("state".to_string(), serde_json::Value::String("InProgress".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: UserInputResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<UserInputResponseDto>::not_found("UserInput", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<UserInputResponseDto>::error(e.to_string()))),
    }
}

/// Execute mark_done transition on a UserInput.
///
/// POST /user_inputs/:id/transitions/mark_done
pub async fn mark_done_transition(
    axum::extract::State(service): axum::extract::State<Arc<UserInputService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] axum::Extension(auth): axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<UserInputResponseDto>::not_found("UserInput", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<UserInputResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = survey_input_stateTransition::MarkDone.allowed_roles();
        let has_specific_perm = auth.permissions.iter().any(|p| p == "user_input:transition:mark_done");
        let has_update_perm = auth.permissions.iter().any(|p| p == "user_input:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<UserInputResponseDto>::error("Insufficient permissions for mark_done transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: survey_input_stateState = entity.state.to_string().parse()
        .unwrap_or(survey_input_stateState::default());
    let sm = survey_input_stateStateMachine::from_state(current_state);
    if !sm.can_transition(survey_input_stateTransition::MarkDone) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<UserInputResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("state".to_string(), serde_json::Value::String("Done".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: UserInputResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<UserInputResponseDto>::not_found("UserInput", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<UserInputResponseDto>::error(e.to_string()))),
    }
}

/// Execute session_bulk_done transition on a UserInput.
///
/// POST /user_inputs/:id/transitions/session_bulk_done
pub async fn session_bulk_done_transition(
    axum::extract::State(service): axum::extract::State<Arc<UserInputService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] axum::Extension(auth): axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<UserInputResponseDto>::not_found("UserInput", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<UserInputResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = survey_input_stateTransition::SessionBulkDone.allowed_roles();
        let has_specific_perm = auth.permissions.iter().any(|p| p == "user_input:transition:session_bulk_done");
        let has_update_perm = auth.permissions.iter().any(|p| p == "user_input:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<UserInputResponseDto>::error("Insufficient permissions for session_bulk_done transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: survey_input_stateState = entity.state.to_string().parse()
        .unwrap_or(survey_input_stateState::default());
    let sm = survey_input_stateStateMachine::from_state(current_state);
    if !sm.can_transition(survey_input_stateTransition::SessionBulkDone) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<UserInputResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("state".to_string(), serde_json::Value::String("Done".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: UserInputResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<UserInputResponseDto>::not_found("UserInput", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<UserInputResponseDto>::error(e.to_string()))),
    }
}

/// Create routes for state transitions.
pub fn create_user_input_transition_routes(service: Arc<UserInputService>) -> Router {
    use axum::routing::post;

    Router::new()
        .route("/user_inputs/:id/transitions/begin", post(begin_transition))
        .route("/user_inputs/:id/transitions/mark_done", post(mark_done_transition))
        .route("/user_inputs/:id/transitions/session_bulk_done", post(session_bulk_done_transition))
        .with_state(service)
}
